#pragma once

#include <array>
#include <cstdint>
#include <string_view>

namespace iee::game::eeex_doc {
    struct FieldDesc {
        std::uint32_t offset{};
        std::uint32_t size{};
        std::string_view type{};
        std::string_view name{};
    };

    struct LayoutDesc {
        std::uint32_t size{};
        std::uint32_t fieldCount{};
    };

    // Generated from EEex-Docs x64 structure tables (commit b1a0ff3, 2025-08-27).
    // Large runtime classes stay available as exact documented field maps so the
    // full EEex surface is in-repo without forcing every nested type into a giant
    // hand-maintained C++ struct mirror.

    inline constexpr std::array<FieldDesc, 128> CInfGameFields{{
        FieldDesc{0x0, 16288, R"eeex(:ref:`CRuleTables<CRuleTables>`)eeex", R"eeex(m_ruleTables)eeex"},
        FieldDesc{0x3FA0, 8, R"eeex(:ref:`CTimerWorld<CTimerWorld>`)eeex", R"eeex(m_worldTime)eeex"},
        FieldDesc{0x3FA8, 4, R"eeex(int)eeex", R"eeex(m_bGameLoaded)eeex"},
        FieldDesc{0x3FAC, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_bInLoadGame)eeex"},
        FieldDesc{0x3FAD, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_bInLoadArea)eeex"},
        FieldDesc{0x3FAE, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_bInIniSpawn)eeex"},
        FieldDesc{0x3FB0, 4, R"eeex(unsigned int)eeex", R"eeex(m_nUniqueAreaID)eeex"},
        FieldDesc{0x3FB4, 4, R"eeex(unsigned int)eeex", R"eeex(m_nAreaFirstObject)eeex"},
        FieldDesc{0x3FB8, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_bFromNewGame)eeex"},
        FieldDesc{0x3FB9, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_bInDestroyGame)eeex"},
        FieldDesc{0x3FBA, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_bAnotherPlayerJoinedGame)eeex"},
        FieldDesc{0x3FBB, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_bInAreaTransition)eeex"},
        FieldDesc{0x3FBC, 4, R"eeex(int)eeex", R"eeex(m_bStartedDeathSequence)eeex"},
        FieldDesc{0x3FC0, 56, R"eeex(:ref:`CTypedPtrList<CTypedPtrList>`\<:ref:`CPtrList<CPtrList>`,long*>)eeex", R"eeex(m_lstTargetIds)eeex"},
        FieldDesc{0x3FF8, 56, R"eeex(:ref:`CTypedPtrList<CTypedPtrList>`\<:ref:`CPtrList<CPtrList>`, :ref:`CPoint<CPoint>`\*>)eeex", R"eeex(m_lstTargetPts)eeex"},
        FieldDesc{0x4030, 2, R"eeex(__int16)eeex", R"eeex(m_nState)eeex"},
        FieldDesc{0x4034, 4, R"eeex(int)eeex", R"eeex(m_iconCount)eeex"},
        FieldDesc{0x4038, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_iconIndex)eeex"},
        FieldDesc{0x4039, 8, R"eeex(:ref:`CResRef<CResRef>`)eeex", R"eeex(m_iconResRef)eeex"},
        FieldDesc{0x4041, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_tempCursor)eeex"},
        FieldDesc{0x4044, 4, R"eeex(int)eeex", R"eeex(m_iContainer)eeex"},
        FieldDesc{0x4048, 4, R"eeex(int)eeex", R"eeex(m_iContainerSprite)eeex"},
        FieldDesc{0x404C, 4, R"eeex(int)eeex", R"eeex(m_bAllowTargetDead)eeex"},
        FieldDesc{0x4050, 8, R"eeex(:ref:`CGamePermission<CGamePermission>`)eeex", R"eeex(m_singlePlayerPermissions)eeex"},
        FieldDesc{0x4058, 208, R"eeex(:ref:`CMultiplayerSettings<CMultiplayerSettings>`)eeex", R"eeex(m_multiPlayerSettings)eeex"},
        FieldDesc{0x4128, 24, R"eeex(:ref:`CMachineStates<CMachineStates>`)eeex", R"eeex(m_machineStates)eeex"},
        FieldDesc{0x4140, 8824, R"eeex(:ref:`CInfButtonArray<CInfButtonArray>`)eeex", R"eeex(m_cButtonArray)eeex"},
        FieldDesc{0x63B8, 16, R"eeex(:ref:`CVRamPool<CVRamPool>`)eeex", R"eeex(m_cVRamPool)eeex"},
        FieldDesc{0x63C8, 4, R"eeex(int)eeex", R"eeex(m_bSaveScreen)eeex"},
        FieldDesc{0x63D0, 8, R"eeex(:ref:`CString<CString>`)eeex", R"eeex(m_sSaveScreenArea)eeex"},
        FieldDesc{0x63D8, 288, R"eeex(:ref:`CVidBitmap<CVidBitmap>`)eeex", R"eeex(m_rgbMasterBitmap)eeex"},
        FieldDesc{0x64F8, 8, R"eeex(:ref:`CGameObjectArray<CGameObjectArray>`)eeex", R"eeex(m_objectsArray)eeex"},
        FieldDesc{0x6500, 144, R"eeex(:ref:`CGameRemoteObjectArray<CGameRemoteObjectArray>`)eeex", R"eeex(m_remoteObjectsArray)eeex"},
        FieldDesc{0x6590, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_visibleArea)eeex"},
        FieldDesc{0x6591, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_bPlayerScriptStyle)eeex"},
        FieldDesc{0x6598, 96, R"eeex(Array<:ref:`CGameArea<CGameArea>`\*,12>)eeex", R"eeex(m_gameAreas)eeex"},
        FieldDesc{0x65F8, 8, R"eeex(:ref:`CGameArea<CGameArea>`\*)eeex", R"eeex(m_pGameAreaMaster)eeex"},
        FieldDesc{0x6600, 24, R"eeex(Array<int,6>)eeex", R"eeex(m_characters)eeex"},
        FieldDesc{0x6618, 24, R"eeex(Array<int,6>)eeex", R"eeex(m_charactersPortrait)eeex"},
        FieldDesc{0x6630, 2, R"eeex(__int16)eeex", R"eeex(m_nCharacters)eeex"},
        FieldDesc{0x6638, 56, R"eeex(:ref:`CTypedPtrList<CTypedPtrList>`\<:ref:`CPtrList<CPtrList>`,long*>)eeex", R"eeex(m_lstGlobalCreatures)eeex"},
        FieldDesc{0x6670, 32, R"eeex(:ref:`CTypedPtrArray<CTypedPtrArray>`\<:ref:`CPtrArray<CPtrArray>`,long*>)eeex", R"eeex(m_characterOverflow)eeex"},
        FieldDesc{0x6690, 2, R"eeex(__int16)eeex", R"eeex(m_nCharacterOverflowCount)eeex"},
        FieldDesc{0x6692, 2, R"eeex(__int16)eeex", R"eeex(m_nReputation)eeex"},
        FieldDesc{0x6698, 8, R"eeex(:ref:`CPathSearch<CPathSearch>`\*)eeex", R"eeex(m_pathSearch)eeex"},
        FieldDesc{0x66A0, 8, R"eeex(:ref:`CPathNode<CPathNode>`\**)eeex", R"eeex(m_listGrid)eeex"},
        FieldDesc{0x66A8, 8, R"eeex(:ref:`CPathNode<CPathNode>`\**)eeex", R"eeex(m_arrayOpenList)eeex"},
        FieldDesc{0x66B0, 64, R"eeex(:ref:`CAIGroup<CAIGroup>`)eeex", R"eeex(m_group)eeex"},
        FieldDesc{0x66F0, 56, R"eeex(:ref:`CTypedPtrList<CTypedPtrList>`\<:ref:`CPtrList<CPtrList>`,long*>)eeex", R"eeex(m_allies)eeex"},
        FieldDesc{0x6728, 56, R"eeex(:ref:`CTypedPtrList<CTypedPtrList>`\<:ref:`CPtrList<CPtrList>`,long*>)eeex", R"eeex(m_familiars)eeex"},
        FieldDesc{0x6760, 72, R"eeex(Array<Array<unsigned __int8,8>,9>)eeex", R"eeex(m_resrefFamiliarsDefault)eeex"},
        FieldDesc{0x67A8, 4536, R"eeex(Array<Array<:ref:`CTypedPtrList<CTypedPtrList>`\<:ref:`CPtrList<CPtrList>`, :ref:`CResRef<CResRef>`\*>,9>,9>)eeex", R"eeex(m_resrefFamiliars)eeex"},
        FieldDesc{0x7960, 4, R"eeex(int)eeex", R"eeex(m_bFamiliarBlock)eeex"},
        FieldDesc{0x7964, 4, R"eeex(unsigned int)eeex", R"eeex(m_nFamiliarSummoner)eeex"},
        FieldDesc{0x7968, 8, R"eeex(:ref:`CString<CString>`)eeex", R"eeex(m_sSaveGame)eeex"},
        FieldDesc{0x7970, 4, R"eeex(int)eeex", R"eeex(m_bAllowCutSceneBreak)eeex"},
        FieldDesc{0x7978, 856, R"eeex(:ref:`CGameSave<CGameSave>`)eeex", R"eeex(m_gameSave)eeex"},
        FieldDesc{0x7CD0, 612, R"eeex(:ref:`CGameOptions<CGameOptions>`)eeex", R"eeex(m_options)eeex"},
        FieldDesc{0x7F38, 40, R"eeex(:ref:`CGameJournal<CGameJournal>`)eeex", R"eeex(m_cGameJournal)eeex"},
        FieldDesc{0x7F60, 40, R"eeex(:ref:`CWorldMap<CWorldMap>`)eeex", R"eeex(m_cWorldMap)eeex"},
        FieldDesc{0x7F88, 2400, R"eeex(Array<int,600>)eeex", R"eeex(m_pKeymap)eeex"},
        FieldDesc{0x88E8, 2400, R"eeex(Array<int,600>)eeex", R"eeex(m_pKeymapFlags)eeex"},
        FieldDesc{0x9248, 16, R"eeex(:ref:`CVariableHash<CVariableHash>`)eeex", R"eeex(m_variables)eeex"},
        FieldDesc{0x9258, 16, R"eeex(:ref:`CVariableHash<CVariableHash>`)eeex", R"eeex(m_namedCreatures)eeex"},
        FieldDesc{0x9268, 40, R"eeex(:ref:`STR_RES<STR_RES>`)eeex", R"eeex(m_soundNeedParty)eeex"},
        FieldDesc{0x9290, 40, R"eeex(:ref:`STR_RES<STR_RES>`)eeex", R"eeex(m_soundAreaTransitionRefused)eeex"},
        FieldDesc{0x92B8, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_bForceDither)eeex"},
        FieldDesc{0x92C0, 312, R"eeex(:ref:`CVidCell<CVidCell>`)eeex", R"eeex(m_vcLocator)eeex"},
        FieldDesc{0x93F8, 56, R"eeex(:ref:`CTypedPtrList<CTypedPtrList>`\<:ref:`CPtrList<CPtrList>`, :ref:`CSearchRequest<CSearchRequest>`\*>)eeex", R"eeex(m_searchRequests)eeex"},
        FieldDesc{0x9430, 56, R"eeex(:ref:`CTypedPtrList<CTypedPtrList>`\<:ref:`CPtrList<CPtrList>`, :ref:`CSearchRequest<CSearchRequest>`\*>)eeex", R"eeex(m_searchRequestsBack)eeex"},
        FieldDesc{0x9468, 4, R"eeex(int)eeex", R"eeex(m_searchRequestListEmpty)eeex"},
        FieldDesc{0x946C, 4, R"eeex(int)eeex", R"eeex(m_searchShutdown)eeex"},
        FieldDesc{0x9470, 56, R"eeex(:ref:`CPtrList<CPtrList>`)eeex", R"eeex(m_lDisposableItems)eeex"},
        FieldDesc{0x94A8, 2, R"eeex(__int16)eeex", R"eeex(m_currArmor)eeex"},
        FieldDesc{0x94AA, 2, R"eeex(__int16)eeex", R"eeex(m_currAnimation)eeex"},
        FieldDesc{0x94B0, 112, R"eeex(:ref:`CAIIdList<CAIIdList>`)eeex", R"eeex(SAVE_OBJECT_LIST)eeex"},
        FieldDesc{0x9520, 4, R"eeex(int)eeex", R"eeex(m_nProtagonistId)eeex"},
        FieldDesc{0x9524, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_bPartyAI)eeex"},
        FieldDesc{0x9525, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_bShowAreaNotes)eeex"},
        FieldDesc{0x9526, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_nTravelScreenImageToUse)eeex"},
        FieldDesc{0x9527, 8, R"eeex(:ref:`CResRef<CResRef>`)eeex", R"eeex(m_resrefTravelScreenImage)eeex"},
        FieldDesc{0x9530, 4, R"eeex(unsigned int)eeex", R"eeex(m_dwLastProgressRenderTickCount)eeex"},
        FieldDesc{0x9534, 4, R"eeex(unsigned int)eeex", R"eeex(m_dwLastProgressMsgTickCount)eeex"},
        FieldDesc{0x9538, 4, R"eeex(unsigned int)eeex", R"eeex(m_nLastSaveTime)eeex"},
        FieldDesc{0x953C, 4, R"eeex(unsigned int)eeex", R"eeex(m_gameTime)eeex"},
        FieldDesc{0x9540, 4, R"eeex(unsigned int)eeex", R"eeex(m_zoomLevel)eeex"},
        FieldDesc{0x9544, 4, R"eeex(unsigned int)eeex", R"eeex(m_zoomEnabled)eeex"},
        FieldDesc{0x9548, 8, R"eeex(:ref:`CPoint<CPoint>`)eeex", R"eeex(m_lastClick)eeex"},
        FieldDesc{0x9550, 4, R"eeex(int)eeex", R"eeex(m_lastTarget)eeex"},
        FieldDesc{0x9554, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_bTriggerOutline)eeex"},
        FieldDesc{0x9558, 48, R"eeex(:ref:`CVidPalette<CVidPalette>`)eeex", R"eeex(m_entanglePalette)eeex"},
        FieldDesc{0x9588, 48, R"eeex(:ref:`CVidPalette<CVidPalette>`)eeex", R"eeex(m_webHoldPalette)eeex"},
        FieldDesc{0x95B8, 4, R"eeex(int)eeex", R"eeex(m_nCharacterTerminationSequenceDelay)eeex"},
        FieldDesc{0x95BC, 4, R"eeex(int)eeex", R"eeex(m_bNoDreamTonight)eeex"},
        FieldDesc{0x95C0, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_bContinueHealing)eeex"},
        FieldDesc{0x95C8, 56, R"eeex(:ref:`CMoveList<CMoveList>`)eeex", R"eeex(m_cMoveList)eeex"},
        FieldDesc{0x9600, 56, R"eeex(:ref:`CMoveList<CMoveList>`)eeex", R"eeex(m_cLimboList)eeex"},
        FieldDesc{0x9638, 56, R"eeex(:ref:`CTypedPtrList<CTypedPtrList>`\<:ref:`CPtrList<CPtrList>`, :ref:`SAreaFileWrapper<SAreaFileWrapper>`\*>)eeex", R"eeex(m_lTransitionPiles)eeex"},
        FieldDesc{0x9670, 8, R"eeex(:ref:`CString<CString>`)eeex", R"eeex(m_transitionPilesResref)eeex"},
        FieldDesc{0x9678, 8, R"eeex(:ref:`CPoint<CPoint>`)eeex", R"eeex(m_transitionPilesPtDest)eeex"},
        FieldDesc{0x9680, 4, R"eeex(int)eeex", R"eeex(m_bMissionPackInfo)eeex"},
        FieldDesc{0x9684, 4, R"eeex(int)eeex", R"eeex(m_bMissionPackInfo25)eeex"},
        FieldDesc{0x9688, 4, R"eeex(int)eeex", R"eeex(m_bMissionPackInfoTBP)eeex"},
        FieldDesc{0x968C, 4, R"eeex(int)eeex", R"eeex(m_nAIIndex)eeex"},
        FieldDesc{0x9690, 4, R"eeex(int)eeex", R"eeex(m_nTimeStop)eeex"},
        FieldDesc{0x9694, 4, R"eeex(int)eeex", R"eeex(m_nTimeStopCaster)eeex"},
        FieldDesc{0x9698, 4, R"eeex(int)eeex", R"eeex(m_nGreyScale)eeex"},
        FieldDesc{0x969C, 4, R"eeex(int)eeex", R"eeex(m_nBrownScale)eeex"},
        FieldDesc{0x96A0, 8, R"eeex(:ref:`CAIScriptFile<CAIScriptFile>`\*)eeex", R"eeex(m_globalScriptFile)eeex"},
        FieldDesc{0x96A8, 96, R"eeex(Array<:ref:`CStore<CStore>`\*,12>)eeex", R"eeex(m_aServerStore)eeex"},
        FieldDesc{0x9708, 12, R"eeex(Array<unsigned __int8,12>)eeex", R"eeex(m_nServerStoreDemands)eeex"},
        FieldDesc{0x9718, 8, R"eeex(:ref:`CString<CString>`)eeex", R"eeex(m_appearanceWeapon)eeex"},
        FieldDesc{0x9720, 8, R"eeex(:ref:`CString<CString>`)eeex", R"eeex(m_appearanceBody)eeex"},
        FieldDesc{0x9728, 8, R"eeex(:ref:`CString<CString>`)eeex", R"eeex(m_appearanceShield)eeex"},
        FieldDesc{0x9730, 8, R"eeex(:ref:`CString<CString>`)eeex", R"eeex(m_appearanceHelmet)eeex"},
        FieldDesc{0x9738, 7, R"eeex(Array<unsigned __int8,7>)eeex", R"eeex(m_appearanceColorsWeapon)eeex"},
        FieldDesc{0x973F, 7, R"eeex(Array<unsigned __int8,7>)eeex", R"eeex(m_appearanceColorsBody)eeex"},
        FieldDesc{0x9746, 7, R"eeex(Array<unsigned __int8,7>)eeex", R"eeex(m_appearanceColorsShield)eeex"},
        FieldDesc{0x974D, 7, R"eeex(Array<unsigned __int8,7>)eeex", R"eeex(m_appearanceColorsHelmet)eeex"},
        FieldDesc{0x9754, 4, R"eeex(int)eeex", R"eeex(m_bOverrideRestEncounter)eeex"},
        FieldDesc{0x9758, 4, R"eeex(int)eeex", R"eeex(m_bAddOnActivated)eeex"},
        FieldDesc{0x975C, 4, R"eeex(int)eeex", R"eeex(m_bAddInActivated)eeex"},
        FieldDesc{0x9760, 8, R"eeex(:ref:`CString<CString>`)eeex", R"eeex(m_sCurrentCampaign)eeex"},
        FieldDesc{0x9768, 4, R"eeex(int)eeex", R"eeex(m_bCampaignEnabled)eeex"},
        FieldDesc{0x9770, 56, R"eeex(:ref:`CTypedPtrList<CTypedPtrList>`\<:ref:`CPtrList<CPtrList>`, :ref:`CSavedGameStoredLocation<CSavedGameStoredLocation>`\*>)eeex", R"eeex(m_storedLocations)eeex"},
        FieldDesc{0x97A8, 56, R"eeex(:ref:`CTypedPtrList<CTypedPtrList>`\<:ref:`CPtrList<CPtrList>`, :ref:`CSavedGameStoredLocation<CSavedGameStoredLocation>`\*>)eeex", R"eeex(m_storedLocationsPocketPlane)eeex"},
        FieldDesc{0x97E0, 16, R"eeex(:ref:`CVVCHash<CVVCHash>`)eeex", R"eeex(m_VVCPriorities)eeex"},
        FieldDesc{0x97F0, 4, R"eeex(int)eeex", R"eeex(m_nCurrentVVCPriority)eeex"},
    }};
    inline constexpr LayoutDesc CInfGameLayout{0x97F8, static_cast<std::uint32_t>(CInfGameFields.size())};

    inline constexpr std::array<FieldDesc, 90> CInfinityFields{{
        FieldDesc{0x0, 40, R"eeex(Array<:ref:`CInfTileSet<CInfTileSet>`\*,5>)eeex", R"eeex(pTileSets)eeex"},
        FieldDesc{0x28, 8, R"eeex(:ref:`CResWED<CResWED>`\*)eeex", R"eeex(pResWED)eeex"},
        FieldDesc{0x30, 8, R"eeex(:ref:`CVRamPool<CVRamPool>`\*)eeex", R"eeex(pVRPool)eeex"},
        FieldDesc{0x38, 8, R"eeex(:ref:`CVidMode<CVidMode>`\*)eeex", R"eeex(pVidMode)eeex"},
        FieldDesc{0x40, 4, R"eeex(int)eeex", R"eeex(bUseDestSrc)eeex"},
        FieldDesc{0x44, 4, R"eeex(int)eeex", R"eeex(bRefreshVRamRect)eeex"},
        FieldDesc{0x48, 4, R"eeex(int)eeex", R"eeex(bInitialized)eeex"},
        FieldDesc{0x4C, 4, R"eeex(int)eeex", R"eeex(bWEDDemanded)eeex"},
        FieldDesc{0x50, 4, R"eeex(int)eeex", R"eeex(nOffsetX)eeex"},
        FieldDesc{0x54, 4, R"eeex(int)eeex", R"eeex(nOffsetY)eeex"},
        FieldDesc{0x58, 4, R"eeex(int)eeex", R"eeex(nTilesX)eeex"},
        FieldDesc{0x5C, 4, R"eeex(int)eeex", R"eeex(nTilesY)eeex"},
        FieldDesc{0x60, 4, R"eeex(int)eeex", R"eeex(nNewX)eeex"},
        FieldDesc{0x64, 4, R"eeex(int)eeex", R"eeex(nNewY)eeex"},
        FieldDesc{0x68, 16, R"eeex(:ref:`CRect<CRect>`)eeex", R"eeex(rViewPortNotZoomed)eeex"},
        FieldDesc{0x78, 16, R"eeex(:ref:`CRect<CRect>`)eeex", R"eeex(rViewPort)eeex"},
        FieldDesc{0x88, 16, R"eeex(:ref:`CRect<CRect>`)eeex", R"eeex(rVRamRect)eeex"},
        FieldDesc{0x98, 16, R"eeex(:ref:`CRect<CRect>`)eeex", R"eeex(rRequestRect)eeex"},
        FieldDesc{0xA8, 4, R"eeex(int)eeex", R"eeex(nVisibleTilesX)eeex"},
        FieldDesc{0xAC, 4, R"eeex(int)eeex", R"eeex(nVisibleTilesY)eeex"},
        FieldDesc{0xB0, 4, R"eeex(int)eeex", R"eeex(nAreaX)eeex"},
        FieldDesc{0xB4, 4, R"eeex(int)eeex", R"eeex(nAreaY)eeex"},
        FieldDesc{0xB8, 4, R"eeex(int)eeex", R"eeex(nCurrentTileX)eeex"},
        FieldDesc{0xBC, 4, R"eeex(int)eeex", R"eeex(nCurrentTileY)eeex"},
        FieldDesc{0xC0, 4, R"eeex(int)eeex", R"eeex(nCurrentX)eeex"},
        FieldDesc{0xC4, 4, R"eeex(int)eeex", R"eeex(nCurrentY)eeex"},
        FieldDesc{0xC8, 4, R"eeex(int)eeex", R"eeex(nSub1XOffset)eeex"},
        FieldDesc{0xCC, 4, R"eeex(int)eeex", R"eeex(nSub1YOffset)eeex"},
        FieldDesc{0xD0, 4, R"eeex(int)eeex", R"eeex(nSub2XOffset)eeex"},
        FieldDesc{0xD4, 4, R"eeex(int)eeex", R"eeex(nSub2YOffset)eeex"},
        FieldDesc{0xD8, 4, R"eeex(int)eeex", R"eeex(nSub3XOffset)eeex"},
        FieldDesc{0xDC, 4, R"eeex(int)eeex", R"eeex(nSub3YOffset)eeex"},
        FieldDesc{0xE0, 4, R"eeex(int)eeex", R"eeex(nSub4XOffset)eeex"},
        FieldDesc{0xE4, 4, R"eeex(int)eeex", R"eeex(nSub4YOffset)eeex"},
        FieldDesc{0xE8, 32, R"eeex(:ref:`CSound<CSound>`)eeex", R"eeex(sndThunder)eeex"},
        FieldDesc{0x108, 4, R"eeex(int)eeex", R"eeex(nCurrentLightningFrequency)eeex"},
        FieldDesc{0x10C, 4, R"eeex(int)eeex", R"eeex(nNextLightningFrequency)eeex"},
        FieldDesc{0x110, 4, R"eeex(int)eeex", R"eeex(nNewLightningFrequency)eeex"},
        FieldDesc{0x114, 4, R"eeex(int)eeex", R"eeex(nCurrentRainLevel)eeex"},
        FieldDesc{0x118, 4, R"eeex(int)eeex", R"eeex(nNextRainLevel)eeex"},
        FieldDesc{0x11C, 4, R"eeex(int)eeex", R"eeex(nCurrentSnowLevel)eeex"},
        FieldDesc{0x120, 4, R"eeex(int)eeex", R"eeex(nCurrentWindLevel)eeex"},
        FieldDesc{0x124, 4, R"eeex(int)eeex", R"eeex(nCurrentFogLevel)eeex"},
        FieldDesc{0x128, 4, R"eeex(int)eeex", R"eeex(nNextWindLevel)eeex"},
        FieldDesc{0x12C, 4, R"eeex(int)eeex", R"eeex(nCurrentTimeOfDay)eeex"},
        FieldDesc{0x130, 4, R"eeex(int)eeex", R"eeex(nTimeToNextThunder)eeex"},
        FieldDesc{0x134, 4, R"eeex(int)eeex", R"eeex(nThunderLength)eeex"},
        FieldDesc{0x138, 4, R"eeex(int)eeex", R"eeex(bRenderCallLightning)eeex"},
        FieldDesc{0x13C, 4, R"eeex(int)eeex", R"eeex(nRenderLightningTimer)eeex"},
        FieldDesc{0x140, 8, R"eeex(:ref:`CPoint<CPoint>`)eeex", R"eeex(cLightningPoint)eeex"},
        FieldDesc{0x148, 312, R"eeex(:ref:`CVidCell<CVidCell>`)eeex", R"eeex(m_glowVidCell)eeex"},
        FieldDesc{0x280, 56, R"eeex(:ref:`CTypedPtrList<CTypedPtrList>`\<:ref:`CPtrList<CPtrList>`, :ref:`CAOEEntry<CAOEEntry>`\*>)eeex", R"eeex(m_lAOE)eeex"},
        FieldDesc{0x2B8, 24, R"eeex(std::vector<unsigned char*,std::allocator<unsigned char*>>)eeex", R"eeex(m_RasterizedPolys)eeex"},
        FieldDesc{0x2D0, 24, R"eeex(std::vector<std::vector<:ref:`WED_PolyPoint_st<WED_PolyPoint_st>`,std::allocator<:ref:`WED_PolyPoint_st<WED_PolyPoint_st>`>>,std::allocator<std::vector<:ref:`WED_PolyPoint_st<WED_PolyPoint_st>`,std::allocator<:ref:`WED_PolyPoint_st<WED_PolyPoint_st>`>>>>)eeex", R"eeex(m_DownsampledPolys)eeex"},
        FieldDesc{0x2E8, 2, R"eeex(unsigned __int16)eeex", R"eeex(m_areaType)eeex"},
        FieldDesc{0x2EA, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_renderDayNightCode)eeex"},
        FieldDesc{0x2EB, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_oldRenderDayNightCode)eeex"},
        FieldDesc{0x2EC, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_dayLightIntensity)eeex"},
        FieldDesc{0x2ED, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_requestDayNightCode)eeex"},
        FieldDesc{0x2EE, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_oldRequestDualTileCode)eeex"},
        FieldDesc{0x2EF, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_bResizedViewPort)eeex"},
        FieldDesc{0x2F0, 4, R"eeex(unsigned int)eeex", R"eeex(m_nLastTickCount)eeex"},
        FieldDesc{0x2F4, 8, R"eeex(:ref:`CPoint<CPoint>`)eeex", R"eeex(m_ptCurrentPosExact)eeex"},
        FieldDesc{0x2FC, 2, R"eeex(__int16)eeex", R"eeex(m_autoScrollSpeed)eeex"},
        FieldDesc{0x300, 8, R"eeex(:ref:`CPoint<CPoint>`)eeex", R"eeex(m_ptScrollDest)eeex"},
        FieldDesc{0x308, 4, R"eeex(int)eeex", R"eeex(m_nScrollAttempts)eeex"},
        FieldDesc{0x30C, 4, R"eeex(int)eeex", R"eeex(m_nOldScrollState)eeex"},
        FieldDesc{0x310, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_nScrollDelay)eeex"},
        FieldDesc{0x311, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_bMovieBroadcast)eeex"},
        FieldDesc{0x314, 4, R"eeex(int)eeex", R"eeex(m_bStartLightning)eeex"},
        FieldDesc{0x318, 4, R"eeex(int)eeex", R"eeex(m_bStopLightning)eeex"},
        FieldDesc{0x31C, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_lightningStrikeProb)eeex"},
        FieldDesc{0x320, 4, R"eeex(unsigned int)eeex", R"eeex(m_rgbRainColor)eeex"},
        FieldDesc{0x324, 4, R"eeex(unsigned int)eeex", R"eeex(m_rgbLightningGlobalLighting)eeex"},
        FieldDesc{0x328, 4, R"eeex(unsigned int)eeex", R"eeex(m_rgbOverCastGlobalLighting)eeex"},
        FieldDesc{0x32C, 4, R"eeex(unsigned int)eeex", R"eeex(m_rgbGlobalLighting)eeex"},
        FieldDesc{0x330, 4, R"eeex(unsigned int)eeex", R"eeex(m_rgbTimeOfDayGlobalLighting)eeex"},
        FieldDesc{0x334, 4, R"eeex(unsigned int)eeex", R"eeex(m_rgbTimeOfDayRainColor)eeex"},
        FieldDesc{0x338, 4, R"eeex(int)eeex", R"eeex(m_updateListenPosition)eeex"},
        FieldDesc{0x340, 8, R"eeex(:ref:`CGameArea<CGameArea>`\*)eeex", R"eeex(m_pArea)eeex"},
        FieldDesc{0x348, 288, R"eeex(:ref:`CVidBitmap<CVidBitmap>`)eeex", R"eeex(m_vbMessageScreen)eeex"},
        FieldDesc{0x468, 4, R"eeex(unsigned int)eeex", R"eeex(m_strrefMessage)eeex"},
        FieldDesc{0x46C, 4, R"eeex(int)eeex", R"eeex(m_bScreenShake)eeex"},
        FieldDesc{0x470, 8, R"eeex(:ref:`CPoint<CPoint>`)eeex", R"eeex(m_screenShakeDelta)eeex"},
        FieldDesc{0x478, 8, R"eeex(:ref:`CPoint<CPoint>`)eeex", R"eeex(m_screenShakeDecrease)eeex"},
        FieldDesc{0x480, 4, R"eeex(float)eeex", R"eeex(m_fZoomSaved)eeex"},
        FieldDesc{0x484, 4, R"eeex(float)eeex", R"eeex(m_fZoom)eeex"},
        FieldDesc{0x488, 4, R"eeex(float)eeex", R"eeex(m_fStoredZoom)eeex"},
        FieldDesc{0x48C, 4, R"eeex(int)eeex", R"eeex(m_bZoomEnabled)eeex"},
        FieldDesc{0x490, 4, R"eeex(int)eeex", R"eeex(m_bZooming)eeex"},
    }};
    inline constexpr LayoutDesc CInfinityLayout{0x498, static_cast<std::uint32_t>(CInfinityFields.size())};

    inline constexpr std::array<FieldDesc, 105> CGameAreaFields{{
        FieldDesc{0x0, 76, R"eeex(:ref:`CAreaFileHeader<CAreaFileHeader>`)eeex", R"eeex(m_header)eeex"},
        FieldDesc{0x4C, 4, R"eeex(int)eeex", R"eeex(m_bHeaderExtendedNight)eeex"},
        FieldDesc{0x50, 144, R"eeex(:ref:`CAreaSoundsAndMusic<CAreaSoundsAndMusic>`)eeex", R"eeex(m_headerSound)eeex"},
        FieldDesc{0xE0, 228, R"eeex(:ref:`CAreaFileRestEncounter<CAreaFileRestEncounter>`)eeex", R"eeex(m_headerRestEncounter)eeex"},
        FieldDesc{0x1C8, 56, R"eeex(:ref:`CTypedPtrList<CTypedPtrList>`\<:ref:`CPtrList<CPtrList>`, :ref:`CAreaFileCharacterEntryPoint<CAreaFileCharacterEntryPoint>`\*>)eeex", R"eeex(m_entryPoints)eeex"},
        FieldDesc{0x200, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_id)eeex"},
        FieldDesc{0x201, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_nCharacters)eeex"},
        FieldDesc{0x202, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_nInfravision)eeex"},
        FieldDesc{0x203, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_bAreaLoaded)eeex"},
        FieldDesc{0x204, 8, R"eeex(:ref:`CResRef<CResRef>`)eeex", R"eeex(m_resref)eeex"},
        FieldDesc{0x20C, 8, R"eeex(:ref:`CResRef<CResRef>`)eeex", R"eeex(m_restMovieDay)eeex"},
        FieldDesc{0x214, 8, R"eeex(:ref:`CResRef<CResRef>`)eeex", R"eeex(m_restMovieNight)eeex"},
        FieldDesc{0x21C, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_waterAlpha)eeex"},
        FieldDesc{0x220, 8, R"eeex(:ref:`CResWED<CResWED>`\*)eeex", R"eeex(m_pResWED)eeex"},
        FieldDesc{0x228, 8, R"eeex(:ref:`CInfGame<CInfGame>`\*)eeex", R"eeex(m_pGame)eeex"},
        FieldDesc{0x230, 4, R"eeex(int)eeex", R"eeex(m_nScrollState)eeex"},
        FieldDesc{0x234, 4, R"eeex(int)eeex", R"eeex(m_nKeyScrollState)eeex"},
        FieldDesc{0x238, 4, R"eeex(int)eeex", R"eeex(m_bSelectionSquareEnabled)eeex"},
        FieldDesc{0x23C, 4, R"eeex(int)eeex", R"eeex(m_bTravelSquare)eeex"},
        FieldDesc{0x240, 4, R"eeex(int)eeex", R"eeex(m_iPickedOnDown)eeex"},
        FieldDesc{0x244, 4, R"eeex(int)eeex", R"eeex(m_iPicked)eeex"},
        FieldDesc{0x248, 4, R"eeex(int)eeex", R"eeex(m_iPickedTarget)eeex"},
        FieldDesc{0x24C, 4, R"eeex(int)eeex", R"eeex(m_bPicked)eeex"},
        FieldDesc{0x250, 4, R"eeex(int)eeex", R"eeex(m_nToolTip)eeex"},
        FieldDesc{0x254, 8, R"eeex(:ref:`CPoint<CPoint>`)eeex", R"eeex(m_mousePos)eeex"},
        FieldDesc{0x260, 288, R"eeex(:ref:`CVidBitmap<CVidBitmap>`)eeex", R"eeex(m_bmLum)eeex"},
        FieldDesc{0x380, 8, R"eeex(:ref:`CVidBitmap<CVidBitmap>`\*)eeex", R"eeex(m_pbmLumNight)eeex"},
        FieldDesc{0x388, 288, R"eeex(:ref:`CVidBitmap<CVidBitmap>`)eeex", R"eeex(m_bmHeight)eeex"},
        FieldDesc{0x4A8, 8, R"eeex(:ref:`CObjectMarker<CObjectMarker>`\*)eeex", R"eeex(m_pObjectMarker)eeex"},
        FieldDesc{0x4B0, 8, R"eeex(:ref:`CObjectMarker<CObjectMarker>`\*)eeex", R"eeex(m_pObjectMarkerHealthBar)eeex"},
        FieldDesc{0x4B8, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_firstRender)eeex"},
        FieldDesc{0x4BC, 16, R"eeex(:ref:`CRect<CRect>`)eeex", R"eeex(m_selectSquare)eeex"},
        FieldDesc{0x4CC, 2, R"eeex(__int16)eeex", R"eeex(m_rotation)eeex"},
        FieldDesc{0x4D0, 8, R"eeex(:ref:`CPoint<CPoint>`)eeex", R"eeex(m_moveDest)eeex"},
        FieldDesc{0x4D8, 4, R"eeex(int)eeex", R"eeex(m_groupMove)eeex"},
        FieldDesc{0x4DC, 16, R"eeex(Array<unsigned __int8,16>)eeex", R"eeex(m_terrainTable)eeex"},
        FieldDesc{0x4EC, 16, R"eeex(Array<unsigned __int8,16>)eeex", R"eeex(m_visibleTerrainTable)eeex"},
        FieldDesc{0x4FC, 4, R"eeex(int)eeex", R"eeex(m_nAIIndex)eeex"},
        FieldDesc{0x500, 4, R"eeex(int)eeex", R"eeex(m_bInPathSearch)eeex"},
        FieldDesc{0x504, 4, R"eeex(unsigned int)eeex", R"eeex(m_nInitialAreaID)eeex"},
        FieldDesc{0x508, 4, R"eeex(unsigned int)eeex", R"eeex(m_nFirstObject)eeex"},
        FieldDesc{0x50C, 4, R"eeex(unsigned int)eeex", R"eeex(m_dwLastProgressRenderTickCount)eeex"},
        FieldDesc{0x510, 4, R"eeex(unsigned int)eeex", R"eeex(m_dwLastProgressMsgTickCount)eeex"},
        FieldDesc{0x514, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_nRandomMonster)eeex"},
        FieldDesc{0x516, 2, R"eeex(__int16)eeex", R"eeex(m_nVisibleMonster)eeex"},
        FieldDesc{0x518, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_bRecentlySaved)eeex"},
        FieldDesc{0x51C, 4, R"eeex(unsigned int)eeex", R"eeex(m_nSavedTime)eeex"},
        FieldDesc{0x520, 168, R"eeex(:ref:`CGameAreaNotes<CGameAreaNotes>`)eeex", R"eeex(m_cGameAreaNotes)eeex"},
        FieldDesc{0x5C8, 1176, R"eeex(:ref:`CInfinity<CInfinity>`)eeex", R"eeex(m_cInfinity)eeex"},
        FieldDesc{0xA60, 336, R"eeex(:ref:`CSearchBitmap<CSearchBitmap>`)eeex", R"eeex(m_search)eeex"},
        FieldDesc{0xBB0, 112, R"eeex(:ref:`CVisibilityMap<CVisibilityMap>`)eeex", R"eeex(m_visibility)eeex"},
        FieldDesc{0xC20, 8, R"eeex(unsigned __int8*)eeex", R"eeex(m_pDynamicHeight)eeex"},
        FieldDesc{0xC28, 4, R"eeex(int)eeex", R"eeex(m_startedMusic)eeex"},
        FieldDesc{0xC2C, 4, R"eeex(unsigned int)eeex", R"eeex(m_startedMusicCounter)eeex"},
        FieldDesc{0xC30, 56, R"eeex(:ref:`CTypedPtrList<CTypedPtrList>`\<:ref:`CPtrList<CPtrList>`,long*>)eeex", R"eeex(m_lVertSort)eeex"},
        FieldDesc{0xC68, 56, R"eeex(:ref:`CTypedPtrList<CTypedPtrList>`\<:ref:`CPtrList<CPtrList>`,long*>)eeex", R"eeex(m_lVertSortBack)eeex"},
        FieldDesc{0xCA0, 56, R"eeex(:ref:`CTypedPtrList<CTypedPtrList>`\<:ref:`CPtrList<CPtrList>`,long*>)eeex", R"eeex(m_lVertSortFlight)eeex"},
        FieldDesc{0xCD8, 56, R"eeex(:ref:`CTypedPtrList<CTypedPtrList>`\<:ref:`CPtrList<CPtrList>`,long*>)eeex", R"eeex(m_lVertSortUnder)eeex"},
        FieldDesc{0xD10, 56, R"eeex(:ref:`CTypedPtrList<CTypedPtrList>`\<:ref:`CPtrList<CPtrList>`,long*>)eeex", R"eeex(m_lVertSortAdd)eeex"},
        FieldDesc{0xD48, 56, R"eeex(:ref:`CTypedPtrList<CTypedPtrList>`\<:ref:`CPtrList<CPtrList>`,long*>)eeex", R"eeex(m_lVertSortBackAdd)eeex"},
        FieldDesc{0xD80, 56, R"eeex(:ref:`CTypedPtrList<CTypedPtrList>`\<:ref:`CPtrList<CPtrList>`,long*>)eeex", R"eeex(m_lVertSortFlightAdd)eeex"},
        FieldDesc{0xDB8, 56, R"eeex(:ref:`CTypedPtrList<CTypedPtrList>`\<:ref:`CPtrList<CPtrList>`,long*>)eeex", R"eeex(m_lVertSortUnderAdd)eeex"},
        FieldDesc{0xDF0, 56, R"eeex(:ref:`CTypedPtrList<CTypedPtrList>`\<:ref:`CPtrList<CPtrList>`,__POSITION*>)eeex", R"eeex(m_lVertSortRemove)eeex"},
        FieldDesc{0xE28, 56, R"eeex(:ref:`CTypedPtrList<CTypedPtrList>`\<:ref:`CPtrList<CPtrList>`,__POSITION*>)eeex", R"eeex(m_lVertSortBackRemove)eeex"},
        FieldDesc{0xE60, 56, R"eeex(:ref:`CTypedPtrList<CTypedPtrList>`\<:ref:`CPtrList<CPtrList>`,__POSITION*>)eeex", R"eeex(m_lVertSortFlightRemove)eeex"},
        FieldDesc{0xE98, 56, R"eeex(:ref:`CTypedPtrList<CTypedPtrList>`\<:ref:`CPtrList<CPtrList>`,__POSITION*>)eeex", R"eeex(m_lVertSortUnderRemove)eeex"},
        FieldDesc{0xED0, 56, R"eeex(:ref:`CTypedPtrList<CTypedPtrList>`\<:ref:`CPtrList<CPtrList>`, :ref:`CTiledObject<CTiledObject>`\*>)eeex", R"eeex(m_lTiledObjects)eeex"},
        FieldDesc{0xF08, 56, R"eeex(:ref:`CTypedPtrList<CTypedPtrList>`\<:ref:`CPtrList<CPtrList>`,long*>)eeex", R"eeex(m_lGameTextObjects)eeex"},
        FieldDesc{0xF40, 56, R"eeex(:ref:`CTypedPtrList<CTypedPtrList>`\<:ref:`CPtrList<CPtrList>`,long*>)eeex", R"eeex(m_lVertSortTransition)eeex"},
        FieldDesc{0xF78, 8, R"eeex(:ref:`CPoint<CPoint>`)eeex", R"eeex(m_ptOldViewPos)eeex"},
        FieldDesc{0xF80, 16, R"eeex(:ref:`CVariableHash<CVariableHash>`)eeex", R"eeex(m_variables)eeex"},
        FieldDesc{0xF90, 16, R"eeex(:ref:`CVariableHash<CVariableHash>`)eeex", R"eeex(m_namedCreatures)eeex"},
        FieldDesc{0xFA0, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_bPermitNewCharacters)eeex"},
        FieldDesc{0xFA2, 2, R"eeex(__int16)eeex", R"eeex(m_nCurrentSong)eeex"},
        FieldDesc{0xFA4, 4, R"eeex(int)eeex", R"eeex(m_nBattleSongCounter)eeex"},
        FieldDesc{0xFA8, 4, R"eeex(int)eeex", R"eeex(m_nDamageCounter)eeex"},
        FieldDesc{0xFAC, 2, R"eeex(__int16)eeex", R"eeex(m_nScreenFlash)eeex"},
        FieldDesc{0xFAE, 2, R"eeex(__int16)eeex", R"eeex(m_nScreenFlashFade)eeex"},
        FieldDesc{0xFB0, 4, R"eeex(unsigned int)eeex", R"eeex(m_screenFlashRGB)eeex"},
        FieldDesc{0xFB8, 56, R"eeex(:ref:`CTypedPtrList<CTypedPtrList>`\<:ref:`CPtrList<CPtrList>`, :ref:`CGameAreaClairvoyanceEntry<CGameAreaClairvoyanceEntry>`\*>)eeex", R"eeex(m_lClairvoyanceObjects)eeex"},
        FieldDesc{0xFF0, 56, R"eeex(:ref:`CTypedPtrList<CTypedPtrList>`\<:ref:`CPtrList<CPtrList>`,long*>)eeex", R"eeex(m_lContainersNeedingUpdate)eeex"},
        FieldDesc{0x1028, 4, R"eeex(int)eeex", R"eeex(m_bAnySpritesInActions)eeex"},
        FieldDesc{0x102C, 4, R"eeex(int)eeex", R"eeex(m_nMPSynchCounter)eeex"},
        FieldDesc{0x1030, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_nMPSignalType)eeex"},
        FieldDesc{0x1031, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_nMPSignalData)eeex"},
        FieldDesc{0x1034, 4, R"eeex(int)eeex", R"eeex(m_nMPSignalsToSend)eeex"},
        FieldDesc{0x1038, 4, R"eeex(int)eeex", R"eeex(m_nEnemyCountWork)eeex"},
        FieldDesc{0x103C, 4, R"eeex(int)eeex", R"eeex(m_nEnemyCountLast)eeex"},
        FieldDesc{0x1040, 4, R"eeex(int)eeex", R"eeex(m_nEnemyCount2ndLast)eeex"},
        FieldDesc{0x1044, 4, R"eeex(int)eeex", R"eeex(m_nEnemyCountSequestered)eeex"},
        FieldDesc{0x1048, 4, R"eeex(int)eeex", R"eeex(m_nTrapCountWork)eeex"},
        FieldDesc{0x104C, 4, R"eeex(int)eeex", R"eeex(m_nTrapCountLast)eeex"},
        FieldDesc{0x1050, 4, R"eeex(int)eeex", R"eeex(m_nTrapCount2ndLast)eeex"},
        FieldDesc{0x1054, 4, R"eeex(int)eeex", R"eeex(m_nUnloadCounter)eeex"},
        FieldDesc{0x1058, 4, R"eeex(int)eeex", R"eeex(m_bDisplayingHealth)eeex"},
        FieldDesc{0x1060, 72, R"eeex(:ref:`CMemINI<CMemINI>`)eeex", R"eeex(INIFile)eeex"},
        FieldDesc{0x10A8, 8, R"eeex(:ref:`CSpawnFile<CSpawnFile>`\*)eeex", R"eeex(mpSpawner)eeex"},
        FieldDesc{0x10B0, 4, R"eeex(int)eeex", R"eeex(m_nCreatureNodeCount)eeex"},
        FieldDesc{0x10B4, 8, R"eeex(:ref:`CSize<CSize>`)eeex", R"eeex(m_lightmapRatio)eeex"},
        FieldDesc{0x10C0, 24, R"eeex(:ref:`CGameArea::m_cWalkableRenderCache_t<CGameArea::\<unnamed_type_m_cWalkableRenderCache\>>`)eeex", R"eeex(m_cWalkableRenderCache)eeex"},
        FieldDesc{0x10D8, 32, R"eeex(:ref:`CSound<CSound>`)eeex", R"eeex(m_sndAmbientDay)eeex"},
        FieldDesc{0x10F8, 32, R"eeex(:ref:`CSound<CSound>`)eeex", R"eeex(m_sndAmbientNight)eeex"},
        FieldDesc{0x1118, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_sndAmbientVolume)eeex"},
        FieldDesc{0x111A, 2, R"eeex(unsigned __int16)eeex", R"eeex(m_sndAmbientDayVolume)eeex"},
        FieldDesc{0x111C, 2, R"eeex(unsigned __int16)eeex", R"eeex(m_sndAmbientNightVolume)eeex"},
    }};
    inline constexpr LayoutDesc CGameAreaLayout{0x1120, static_cast<std::uint32_t>(CGameAreaFields.size())};

    inline constexpr std::array<FieldDesc, 339> CGameSpriteFields{{
        FieldDesc{0x0, 1344, R"eeex(:ref:`CGameAIBase<CGameAIBase>`)eeex", R"eeex(baseclass_0)eeex"},
        FieldDesc{0x540, 8, R"eeex(:ref:`CResRef<CResRef>`)eeex", R"eeex(m_resref)eeex"},
        FieldDesc{0x548, 2, R"eeex(unsigned __int16)eeex", R"eeex(m_type)eeex"},
        FieldDesc{0x54C, 4, R"eeex(unsigned int)eeex", R"eeex(m_expirationTime)eeex"},
        FieldDesc{0x550, 2, R"eeex(unsigned __int16)eeex", R"eeex(m_huntingRange)eeex"},
        FieldDesc{0x552, 2, R"eeex(unsigned __int16)eeex", R"eeex(m_followRange)eeex"},
        FieldDesc{0x554, 8, R"eeex(:ref:`CPoint<CPoint>`)eeex", R"eeex(m_posStart)eeex"},
        FieldDesc{0x55C, 4, R"eeex(unsigned int)eeex", R"eeex(m_timeOfDayVisible)eeex"},
        FieldDesc{0x560, 616, R"eeex(:ref:`CCreatureFileHeader<CCreatureFileHeader>`)eeex", R"eeex(m_baseStats)eeex"},
        FieldDesc{0x7C8, 392, R"eeex(Array<:ref:`CTypedPtrList<CTypedPtrList>`\<:ref:`CPtrList<CPtrList>`, :ref:`CCreatureFileKnownSpell<CCreatureFileKnownSpell>`\*>,7>)eeex", R"eeex(m_knownSpellsPriest)eeex"},
        FieldDesc{0x950, 504, R"eeex(Array<:ref:`CTypedPtrList<CTypedPtrList>`\<:ref:`CPtrList<CPtrList>`, :ref:`CCreatureFileKnownSpell<CCreatureFileKnownSpell>`\*>,9>)eeex", R"eeex(m_knownSpellsMage)eeex"},
        FieldDesc{0xB48, 56, R"eeex(Array<:ref:`CTypedPtrList<CTypedPtrList>`\<:ref:`CPtrList<CPtrList>`, :ref:`CCreatureFileKnownSpell<CCreatureFileKnownSpell>`\*>,1>)eeex", R"eeex(m_knownSpellsInnate)eeex"},
        FieldDesc{0xB80, 56, R"eeex(Array<:ref:`CCreatureFileMemorizedSpellLevel<CCreatureFileMemorizedSpellLevel>`\*,7>)eeex", R"eeex(m_memorizedSpellsLevelPriest)eeex"},
        FieldDesc{0xBB8, 72, R"eeex(Array<:ref:`CCreatureFileMemorizedSpellLevel<CCreatureFileMemorizedSpellLevel>`\*,9>)eeex", R"eeex(m_memorizedSpellsLevelMage)eeex"},
        FieldDesc{0xC00, 8, R"eeex(Array<:ref:`CCreatureFileMemorizedSpellLevel<CCreatureFileMemorizedSpellLevel>`\*,1>)eeex", R"eeex(m_memorizedSpellsLevelInnate)eeex"},
        FieldDesc{0xC08, 392, R"eeex(Array<:ref:`CTypedPtrList<CTypedPtrList>`\<:ref:`CPtrList<CPtrList>`, :ref:`CCreatureFileMemorizedSpell<CCreatureFileMemorizedSpell>`\*>,7>)eeex", R"eeex(m_memorizedSpellsPriest)eeex"},
        FieldDesc{0xD90, 504, R"eeex(Array<:ref:`CTypedPtrList<CTypedPtrList>`\<:ref:`CPtrList<CPtrList>`, :ref:`CCreatureFileMemorizedSpell<CCreatureFileMemorizedSpell>`\*>,9>)eeex", R"eeex(m_memorizedSpellsMage)eeex"},
        FieldDesc{0xF88, 56, R"eeex(Array<:ref:`CTypedPtrList<CTypedPtrList>`\<:ref:`CPtrList<CPtrList>`, :ref:`CCreatureFileMemorizedSpell<CCreatureFileMemorizedSpell>`\*>,1>)eeex", R"eeex(m_memorizedSpellsInnate)eeex"},
        FieldDesc{0xFC0, 336, R"eeex(:ref:`CGameSpriteEquipment<CGameSpriteEquipment>`)eeex", R"eeex(m_equipment)eeex"},
        FieldDesc{0x1110, 8, R"eeex(unsigned __int8*)eeex", R"eeex(m_pDialogData)eeex"},
        FieldDesc{0x1118, 4, R"eeex(unsigned int)eeex", R"eeex(m_nDialogData)eeex"},
        FieldDesc{0x1120, 3240, R"eeex(:ref:`CDerivedStats<CDerivedStats>`)eeex", R"eeex(m_derivedStats)eeex"},
        FieldDesc{0x1DC8, 3240, R"eeex(:ref:`CDerivedStats<CDerivedStats>`)eeex", R"eeex(m_tempStats)eeex"},
        FieldDesc{0x2A70, 3240, R"eeex(:ref:`CDerivedStats<CDerivedStats>`)eeex", R"eeex(m_bonusStats)eeex"},
        FieldDesc{0x3718, 524, R"eeex(:ref:`CGameSaveCharacter<CGameSaveCharacter>`)eeex", R"eeex(m_gameSaveData)eeex"},
        FieldDesc{0x3928, 8, R"eeex(:ref:`CString<CString>`)eeex", R"eeex(m_sName)eeex"},
        FieldDesc{0x3930, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_lastCharacterCount)eeex"},
        FieldDesc{0x3938, 232, R"eeex(:ref:`CGameStatsSprite<CGameStatsSprite>`)eeex", R"eeex(m_cGameStats)eeex"},
        FieldDesc{0x3A20, 8, R"eeex(:ref:`CResRef<CResRef>`)eeex", R"eeex(m_currentArea)eeex"},
        FieldDesc{0x3A28, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_bGlobal)eeex"},
        FieldDesc{0x3A29, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_nModalState)eeex"},
        FieldDesc{0x3A30, 64, R"eeex(Array<:ref:`CSound<CSound>`,2>)eeex", R"eeex(m_sndWalk)eeex"},
        FieldDesc{0x3A70, 4, R"eeex(unsigned int)eeex", R"eeex(m_nSndWalk)eeex"},
        FieldDesc{0x3A78, 64, R"eeex(Array<:ref:`CSound<CSound>`,2>)eeex", R"eeex(m_sndArmor)eeex"},
        FieldDesc{0x3AB8, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_currSndWalk)eeex"},
        FieldDesc{0x3AB9, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_currSndArmor)eeex"},
        FieldDesc{0x3AC0, 32, R"eeex(:ref:`CSound<CSound>`)eeex", R"eeex(m_sndReady)eeex"},
        FieldDesc{0x3AE0, 32, R"eeex(:ref:`CSound<CSound>`)eeex", R"eeex(m_sndDeath)eeex"},
        FieldDesc{0x3B00, 32, R"eeex(:ref:`CSound<CSound>`)eeex", R"eeex(m_sndMagic)eeex"},
        FieldDesc{0x3B20, 32, R"eeex(:ref:`CSound<CSound>`)eeex", R"eeex(m_sndVoice)eeex"},
        FieldDesc{0x3B40, 32, R"eeex(:ref:`CSound<CSound>`)eeex", R"eeex(m_sndSpriteEffect)eeex"},
        FieldDesc{0x3B60, 4, R"eeex(int)eeex", R"eeex(m_nNumberOfTimesTalkedTo)eeex"},
        FieldDesc{0x3B64, 4, R"eeex(int)eeex", R"eeex(m_bSeenPartyBefore)eeex"},
        FieldDesc{0x3B68, 8, R"eeex(:ref:`CResRef<CResRef>`)eeex", R"eeex(m_specificScriptName)eeex"},
        FieldDesc{0x3B70, 96, R"eeex(Array<int,24>)eeex", R"eeex(m_nNumberOfTimesInteractedWith)eeex"},
        FieldDesc{0x3BD0, 2, R"eeex(__int16)eeex", R"eeex(m_nHappiness)eeex"},
        FieldDesc{0x3BD2, 2, R"eeex(__int16)eeex", R"eeex(m_nOldHappiness)eeex"},
        FieldDesc{0x3BD8, 24, R"eeex(:ref:`CAIObjectType<CAIObjectType>`)eeex", R"eeex(m_interactingWith)eeex"},
        FieldDesc{0x3BF0, 4, R"eeex(int)eeex", R"eeex(m_triggerId)eeex"},
        FieldDesc{0x3BF4, 4, R"eeex(int)eeex", R"eeex(m_active)eeex"},
        FieldDesc{0x3BF8, 4, R"eeex(int)eeex", R"eeex(m_activeAI)eeex"},
        FieldDesc{0x3BFC, 4, R"eeex(int)eeex", R"eeex(m_activeImprisonment)eeex"},
        FieldDesc{0x3C00, 4, R"eeex(int)eeex", R"eeex(m_bSelected)eeex"},
        FieldDesc{0x3C04, 4, R"eeex(int)eeex", R"eeex(m_bPortraitUpdate)eeex"},
        FieldDesc{0x3C08, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_bInfravisionOn)eeex"},
        FieldDesc{0x3C09, 16, R"eeex(Array<unsigned __int8,16>)eeex", R"eeex(m_terrainTable)eeex"},
        FieldDesc{0x3C19, 16, R"eeex(Array<unsigned __int8,16>)eeex", R"eeex(m_visibleTerrainTable)eeex"},
        FieldDesc{0x3C29, 16, R"eeex(Array<unsigned __int8,16>)eeex", R"eeex(m_flightTerrainTable)eeex"},
        FieldDesc{0x3C40, 24, R"eeex(:ref:`CGameAnimation<CGameAnimation>`)eeex", R"eeex(m_animation)eeex"},
        FieldDesc{0x3C58, 8, R"eeex(unsigned __int16*)eeex", R"eeex(m_pSpriteEffectArray)eeex"},
        FieldDesc{0x3C60, 8, R"eeex(tagPOINT*)eeex", R"eeex(m_pSpriteEffectArrayPosition)eeex"},
        FieldDesc{0x3C68, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_nTwitches)eeex"},
        FieldDesc{0x3C69, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_spriteEffectSequenceNumber)eeex"},
        FieldDesc{0x3C6A, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_spriteEffectDuration)eeex"},
        FieldDesc{0x3C6B, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_spriteEffectSequenceLength)eeex"},
        FieldDesc{0x3C6C, 1, R"eeex(char)eeex", R"eeex(m_spriteEffectBaseIntensity)eeex"},
        FieldDesc{0x3C6D, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_spriteEffectRandomIntensity)eeex"},
        FieldDesc{0x3C70, 312, R"eeex(:ref:`CVidCell<CVidCell>`)eeex", R"eeex(m_spriteEffectVidCell)eeex"},
        FieldDesc{0x3DA8, 48, R"eeex(:ref:`CVidPalette<CVidPalette>`)eeex", R"eeex(m_spriteEffectPalette)eeex"},
        FieldDesc{0x3DD8, 4, R"eeex(unsigned int)eeex", R"eeex(m_spriteEffectFlags)eeex"},
        FieldDesc{0x3DE0, 312, R"eeex(:ref:`CVidCell<CVidCell>`)eeex", R"eeex(m_spriteSplashVidCell)eeex"},
        FieldDesc{0x3F18, 48, R"eeex(:ref:`CVidPalette<CVidPalette>`)eeex", R"eeex(m_spriteSplashPalette)eeex"},
        FieldDesc{0x3F48, 4, R"eeex(unsigned int)eeex", R"eeex(m_spriteSplashFlags)eeex"},
        FieldDesc{0x3F4C, 16, R"eeex(:ref:`CRect<CRect>`)eeex", R"eeex(m_rSpriteEffectFX)eeex"},
        FieldDesc{0x3F5C, 8, R"eeex(:ref:`CPoint<CPoint>`)eeex", R"eeex(m_ptSpriteEffectReference)eeex"},
        FieldDesc{0x3F64, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_effectExtendDirection)eeex"},
        FieldDesc{0x3F65, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_bEscapingArea)eeex"},
        FieldDesc{0x3F68, 4, R"eeex(int)eeex", R"eeex(m_animationRunning)eeex"},
        FieldDesc{0x3F6C, 4, R"eeex(int)eeex", R"eeex(m_posZDelta)eeex"},
        FieldDesc{0x3F70, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_doBounce)eeex"},
        FieldDesc{0x3F71, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_nMirrorImages)eeex"},
        FieldDesc{0x3F72, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_bBlur)eeex"},
        FieldDesc{0x3F73, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_bInvisible)eeex"},
        FieldDesc{0x3F74, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_bSanctuary)eeex"},
        FieldDesc{0x3F78, 312, R"eeex(:ref:`CVidCell<CVidCell>`)eeex", R"eeex(m_sanctuaryVidCell)eeex"},
        FieldDesc{0x40B0, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_bEntangle)eeex"},
        FieldDesc{0x40B8, 312, R"eeex(:ref:`CVidCell<CVidCell>`)eeex", R"eeex(m_entangleVidCell)eeex"},
        FieldDesc{0x41F0, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_bMinorGlobe)eeex"},
        FieldDesc{0x41F8, 312, R"eeex(:ref:`CVidCell<CVidCell>`)eeex", R"eeex(m_minorGlobeVidCell)eeex"},
        FieldDesc{0x4330, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_bShieldGlobe)eeex"},
        FieldDesc{0x4338, 312, R"eeex(:ref:`CVidCell<CVidCell>`)eeex", R"eeex(m_shieldGlobeVidCell)eeex"},
        FieldDesc{0x4470, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_bGreasePool)eeex"},
        FieldDesc{0x4478, 312, R"eeex(:ref:`CVidCell<CVidCell>`)eeex", R"eeex(m_greasePoolVidCell)eeex"},
        FieldDesc{0x45B0, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_bWebHold)eeex"},
        FieldDesc{0x45B8, 312, R"eeex(:ref:`CVidCell<CVidCell>`)eeex", R"eeex(m_webHoldVidCell)eeex"},
        FieldDesc{0x46F0, 8, R"eeex(long double)eeex", R"eeex(m_fCircleChange)eeex"},
        FieldDesc{0x46F8, 8, R"eeex(long double)eeex", R"eeex(m_fCurrCircleChange)eeex"},
        FieldDesc{0x4700, 2, R"eeex(__int16)eeex", R"eeex(m_radius)eeex"},
        FieldDesc{0x4702, 1, R"eeex(char)eeex", R"eeex(m_circleFacing)eeex"},
        FieldDesc{0x4703, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_bVisibilityUpdated)eeex"},
        FieldDesc{0x4708, 8, R"eeex(long double)eeex", R"eeex(m_fDirectionOffset)eeex"},
        FieldDesc{0x4710, 2, R"eeex(__int16)eeex", R"eeex(m_nSequence)eeex"},
        FieldDesc{0x4714, 8, R"eeex(:ref:`CPoint<CPoint>`)eeex", R"eeex(m_posExact)eeex"},
        FieldDesc{0x471C, 8, R"eeex(:ref:`CPoint<CPoint>`)eeex", R"eeex(m_posDelta)eeex"},
        FieldDesc{0x4724, 8, R"eeex(:ref:`CPoint<CPoint>`)eeex", R"eeex(m_posDest)eeex"},
        FieldDesc{0x472C, 8, R"eeex(:ref:`CPoint<CPoint>`)eeex", R"eeex(m_posOld)eeex"},
        FieldDesc{0x4734, 8, R"eeex(:ref:`CPoint<CPoint>`)eeex", R"eeex(m_posOldWalk)eeex"},
        FieldDesc{0x473C, 8, R"eeex(:ref:`CPoint<CPoint>`)eeex", R"eeex(m_posLastVisMapEntry)eeex"},
        FieldDesc{0x4748, 8, R"eeex(int*)eeex", R"eeex(m_pVisMapExploredArea)eeex"},
        FieldDesc{0x4750, 2, R"eeex(__int16)eeex", R"eeex(m_skipDeltaDirection)eeex"},
        FieldDesc{0x4752, 2, R"eeex(__int16)eeex", R"eeex(m_deltaDirection)eeex"},
        FieldDesc{0x4754, 2, R"eeex(__int16)eeex", R"eeex(m_nNewDirection)eeex"},
        FieldDesc{0x4756, 2, R"eeex(__int16)eeex", R"eeex(m_nDirection)eeex"},
        FieldDesc{0x4758, 8, R"eeex(int*)eeex", R"eeex(m_pPath)eeex"},
        FieldDesc{0x4760, 2, R"eeex(__int16)eeex", R"eeex(m_nPath)eeex"},
        FieldDesc{0x4762, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_bCheckMove)eeex"},
        FieldDesc{0x4768, 56, R"eeex(:ref:`CTypedPtrList<CTypedPtrList>`\<:ref:`CPtrList<CPtrList>`,long*>)eeex", R"eeex(m_pPathTemp)eeex"},
        FieldDesc{0x47A0, 56, R"eeex(:ref:`CTypedPtrList<CTypedPtrList>`\<:ref:`CPtrList<CPtrList>`,long*>)eeex", R"eeex(m_nPathTemp)eeex"},
        FieldDesc{0x47D8, 2, R"eeex(__int16)eeex", R"eeex(m_currPath)eeex"},
        FieldDesc{0x47DC, 4, R"eeex(int)eeex", R"eeex(m_walkBackwards)eeex"},
        FieldDesc{0x47E0, 4, R"eeex(int)eeex", R"eeex(m_turningAbout)eeex"},
        FieldDesc{0x47E4, 4, R"eeex(unsigned int)eeex", R"eeex(m_lastRGBColor)eeex"},
        FieldDesc{0x47E8, 4, R"eeex(int)eeex", R"eeex(m_pathSearchInvalidDest)eeex"},
        FieldDesc{0x47EC, 4, R"eeex(int)eeex", R"eeex(m_pathCollision)eeex"},
        FieldDesc{0x47F0, 8, R"eeex(:ref:`CSearchRequest<CSearchRequest>`\*)eeex", R"eeex(m_currentSearchRequest)eeex"},
        FieldDesc{0x47F8, 2, R"eeex(__int16)eeex", R"eeex(m_nBloodFlashAmount)eeex"},
        FieldDesc{0x47FA, 2, R"eeex(__int16)eeex", R"eeex(m_nDamageLocatorTime)eeex"},
        FieldDesc{0x47FC, 4, R"eeex(unsigned int)eeex", R"eeex(m_nDamageLocatorColor)eeex"},
        FieldDesc{0x4800, 4, R"eeex(int)eeex", R"eeex(m_bBloodFlashOn)eeex"},
        FieldDesc{0x4808, 288, R"eeex(:ref:`CVidBitmap<CVidBitmap>`)eeex", R"eeex(m_vbPortraitSmall)eeex"},
        FieldDesc{0x4928, 4, R"eeex(int)eeex", R"eeex(m_bVisibleMonster)eeex"},
        FieldDesc{0x492C, 4, R"eeex(int)eeex", R"eeex(m_bBumpable)eeex"},
        FieldDesc{0x4930, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_bBumped)eeex"},
        FieldDesc{0x4934, 8, R"eeex(:ref:`CPoint<CPoint>`)eeex", R"eeex(m_ptBumpedFrom)eeex"},
        FieldDesc{0x493C, 4, R"eeex(int)eeex", R"eeex(m_bInClearBumpPath)eeex"},
        FieldDesc{0x4940, 4, R"eeex(unsigned int)eeex", R"eeex(m_nBlockedTick)eeex"},
        FieldDesc{0x4944, 4, R"eeex(int)eeex", R"eeex(m_followLeader)eeex"},
        FieldDesc{0x4948, 4, R"eeex(int)eeex", R"eeex(m_followLeaderAdditive)eeex"},
        FieldDesc{0x494C, 4, R"eeex(int)eeex", R"eeex(m_followLeaderNext)eeex"},
        FieldDesc{0x4950, 4, R"eeex(int)eeex", R"eeex(m_followStart)eeex"},
        FieldDesc{0x4958, 56, R"eeex(:ref:`CTypedPtrList<CTypedPtrList>`\<:ref:`CPtrList<CPtrList>`, :ref:`CBlood<CBlood>`\*>)eeex", R"eeex(m_lstBlood)eeex"},
        FieldDesc{0x4990, 2, R"eeex(__int16)eeex", R"eeex(m_castCounter)eeex"},
        FieldDesc{0x4994, 4, R"eeex(int)eeex", R"eeex(m_bStartedCasting)eeex"},
        FieldDesc{0x4998, 4, R"eeex(int)eeex", R"eeex(m_bInCasting)eeex"},
        FieldDesc{0x499C, 2, R"eeex(__int16)eeex", R"eeex(m_selectedSound)eeex"},
        FieldDesc{0x499E, 2, R"eeex(__int16)eeex", R"eeex(m_moveCount)eeex"},
        FieldDesc{0x49A0, 2, R"eeex(__int16)eeex", R"eeex(m_moveToFrontQueue)eeex"},
        FieldDesc{0x49A2, 2, R"eeex(__int16)eeex", R"eeex(m_moveToBackQueue)eeex"},
        FieldDesc{0x49A4, 4, R"eeex(int)eeex", R"eeex(m_moveToBack)eeex"},
        FieldDesc{0x49A8, 4, R"eeex(int)eeex", R"eeex(m_moveToFront)eeex"},
        FieldDesc{0x49B0, 80, R"eeex(:ref:`CGameEffectList<CGameEffectList>`)eeex", R"eeex(m_equipedEffectList)eeex"},
        FieldDesc{0x4A00, 80, R"eeex(:ref:`CGameEffectList<CGameEffectList>`)eeex", R"eeex(m_timedEffectList)eeex"},
        FieldDesc{0x4A50, 56, R"eeex(:ref:`CPersistantEffectList<CPersistantEffectList>`)eeex", R"eeex(m_persistantEffects)eeex"},
        FieldDesc{0x4A88, 32, R"eeex(:ref:`CGameAbilityList<CGameAbilityList>`)eeex", R"eeex(m_lstSelectedLevelUpAbilities)eeex"},
        FieldDesc{0x4AA8, 8, R"eeex(:ref:`CPoint<CPoint>`)eeex", R"eeex(m_curDest)eeex"},
        FieldDesc{0x4AB0, 4, R"eeex(int)eeex", R"eeex(m_nGregsRetryCounter)eeex"},
        FieldDesc{0x4AB4, 4, R"eeex(int)eeex", R"eeex(m_bWaitingForAreaLoadInLeaveAreaLUA)eeex"},
        FieldDesc{0x4AB8, 2, R"eeex(__int16)eeex", R"eeex(m_userCommandPause)eeex"},
        FieldDesc{0x4ABA, 2, R"eeex(__int16)eeex", R"eeex(m_nCommandPause)eeex"},
        FieldDesc{0x4ABC, 8, R"eeex(:ref:`CPoint<CPoint>`)eeex", R"eeex(m_curPosition)eeex"},
        FieldDesc{0x4AC4, 4, R"eeex(int)eeex", R"eeex(m_tookDamage)eeex"},
        FieldDesc{0x4AC8, 8, R"eeex(__POSITION*)eeex", R"eeex(m_groupPosition)eeex"},
        FieldDesc{0x4AD0, 4, R"eeex(int)eeex", R"eeex(m_groupMove)eeex"},
        FieldDesc{0x4AD4, 4, R"eeex(int)eeex", R"eeex(m_firstDeadAI)eeex"},
        FieldDesc{0x4AD8, 8, R"eeex(:ref:`CProjectile<CProjectile>`\*)eeex", R"eeex(m_curProjectile)eeex"},
        FieldDesc{0x4AE0, 8, R"eeex(:ref:`CSpell<CSpell>`\*)eeex", R"eeex(m_curSpell)eeex"},
        FieldDesc{0x4AE8, 8, R"eeex(:ref:`CItem<CItem>`\*)eeex", R"eeex(m_curItem)eeex"},
        FieldDesc{0x4AF0, 2, R"eeex(__int16)eeex", R"eeex(m_curItemSlotNum)eeex"},
        FieldDesc{0x4AF2, 2, R"eeex(__int16)eeex", R"eeex(m_curItemAbilityNum)eeex"},
        FieldDesc{0x4AF4, 80, R"eeex(Array<__int16,40>)eeex", R"eeex(m_weaponProficiencyList)eeex"},
        FieldDesc{0x4B44, 8, R"eeex(Array<unsigned __int8,8>)eeex", R"eeex(m_generalWeaponList)eeex"},
        FieldDesc{0x4B4C, 2, R"eeex(__int16)eeex", R"eeex(m_speedFactor)eeex"},
        FieldDesc{0x4B4E, 2, R"eeex(__int16)eeex", R"eeex(m_lastActionID)eeex"},
        FieldDesc{0x4B50, 24, R"eeex(:ref:`CAIObjectType<CAIObjectType>`)eeex", R"eeex(m_liveTypeAI)eeex"},
        FieldDesc{0x4B68, 24, R"eeex(:ref:`CAIObjectType<CAIObjectType>`)eeex", R"eeex(m_startTypeAI)eeex"},
        FieldDesc{0x4B80, 4, R"eeex(int)eeex", R"eeex(m_endOfDamageSeq)eeex"},
        FieldDesc{0x4B84, 2, R"eeex(__int16)eeex", R"eeex(m_playDeadCounter)eeex"},
        FieldDesc{0x4B86, 2, R"eeex(__int16)eeex", R"eeex(m_turnToStoneCounter)eeex"},
        FieldDesc{0x4B88, 2, R"eeex(__int16)eeex", R"eeex(m_lightningReactCounter)eeex"},
        FieldDesc{0x4B8A, 2, R"eeex(__int16)eeex", R"eeex(m_sleepCounter)eeex"},
        FieldDesc{0x4B8C, 2, R"eeex(__int16)eeex", R"eeex(m_runCounter)eeex"},
        FieldDesc{0x4B8E, 2, R"eeex(__int16)eeex", R"eeex(m_searchPauseCount)eeex"},
        FieldDesc{0x4B90, 4, R"eeex(int)eeex", R"eeex(m_doneSearch)eeex"},
        FieldDesc{0x4B94, 2, R"eeex(__int16)eeex", R"eeex(m_dieCount)eeex"},
        FieldDesc{0x4B96, 2, R"eeex(__int16)eeex", R"eeex(m_pauseCount)eeex"},
        FieldDesc{0x4B98, 2, R"eeex(__int16)eeex", R"eeex(m_recoilFrame)eeex"},
        FieldDesc{0x4B9A, 2, R"eeex(__int16)eeex", R"eeex(m_attackFrame)eeex"},
        FieldDesc{0x4B9C, 4, R"eeex(int)eeex", R"eeex(m_noActionCount)eeex"},
        FieldDesc{0x4BA0, 4, R"eeex(int)eeex", R"eeex(m_inFormation)eeex"},
        FieldDesc{0x4BA4, 4, R"eeex(int)eeex", R"eeex(m_newEffect)eeex"},
        FieldDesc{0x4BA8, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_canDamage)eeex"},
        FieldDesc{0x4BAC, 4, R"eeex(int)eeex", R"eeex(m_leftAttack)eeex"},
        FieldDesc{0x4BB0, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_halfAttack)eeex"},
        FieldDesc{0x4BB4, 4, R"eeex(int)eeex", R"eeex(m_hasColorEffects)eeex"},
        FieldDesc{0x4BB8, 4, R"eeex(int)eeex", R"eeex(m_hasColorRangeEffects)eeex"},
        FieldDesc{0x4BBC, 4, R"eeex(int)eeex", R"eeex(m_hasAnimationEffects)eeex"},
        FieldDesc{0x4BC0, 4, R"eeex(int)eeex", R"eeex(m_removeFromArea)eeex"},
        FieldDesc{0x4BC4, 4, R"eeex(int)eeex", R"eeex(m_forceAnimationReset)eeex"},
        FieldDesc{0x4BC8, 44, R"eeex(:ref:`CMarker<CMarker>`)eeex", R"eeex(m_marker)eeex"},
        FieldDesc{0x4BF4, 44, R"eeex(:ref:`CMarker<CMarker>`)eeex", R"eeex(m_destMarker)eeex"},
        FieldDesc{0x4C20, 4, R"eeex(int)eeex", R"eeex(m_targetId)eeex"},
        FieldDesc{0x4C24, 8, R"eeex(:ref:`CPoint<CPoint>`)eeex", R"eeex(m_targetPoint)eeex"},
        FieldDesc{0x4C2C, 2, R"eeex(__int16)eeex", R"eeex(m_targetAreaSize)eeex"},
        FieldDesc{0x4C2E, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_nTempSelectedWeapon)eeex"},
        FieldDesc{0x4C2F, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_nTempSelectedWeaponAbility)eeex"},
        FieldDesc{0x4C30, 52, R"eeex(:ref:`CButtonData<CButtonData>`)eeex", R"eeex(m_currentUseButton)eeex"},
        FieldDesc{0x4C64, 8, R"eeex(:ref:`CResRef<CResRef>`)eeex", R"eeex(m_dialog)eeex"},
        FieldDesc{0x4C6C, 8, R"eeex(:ref:`CResRef<CResRef>`)eeex", R"eeex(m_dialogInteraction)eeex"},
        FieldDesc{0x4C74, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_sequenceTest)eeex"},
        FieldDesc{0x4C78, 8, R"eeex(:ref:`STR_RES<STR_RES>`\*)eeex", R"eeex(m_speech)eeex"},
        FieldDesc{0x4C80, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_saveVSDeathRoll)eeex"},
        FieldDesc{0x4C81, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_saveVSWandsRoll)eeex"},
        FieldDesc{0x4C82, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_saveVSPolyRoll)eeex"},
        FieldDesc{0x4C83, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_saveVSBreathRoll)eeex"},
        FieldDesc{0x4C84, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_saveVSSpellRoll)eeex"},
        FieldDesc{0x4C85, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_magicResistRoll)eeex"},
        FieldDesc{0x4C86, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_probabilityRoll)eeex"},
        FieldDesc{0x4C87, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_wildMageLevelModRoll)eeex"},
        FieldDesc{0x4C88, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_wildMageSurgeRoll)eeex"},
        FieldDesc{0x4C8A, 2, R"eeex(__int16)eeex", R"eeex(m_wildSurgeLevel)eeex"},
        FieldDesc{0x4C8C, 2, R"eeex(__int16)eeex", R"eeex(m_nSelectionCountCommon)eeex"},
        FieldDesc{0x4C8E, 2, R"eeex(__int16)eeex", R"eeex(m_nSelectionCountCommonRareCounter)eeex"},
        FieldDesc{0x4C90, 2, R"eeex(__int16)eeex", R"eeex(m_nSelectionCountRare)eeex"},
        FieldDesc{0x4C92, 2, R"eeex(__int16)eeex", R"eeex(m_nSelectionCountAction)eeex"},
        FieldDesc{0x4C94, 2, R"eeex(__int16)eeex", R"eeex(m_nSelectionCountActionRareCounter)eeex"},
        FieldDesc{0x4C98, 4, R"eeex(int)eeex", R"eeex(m_lastCheckedHitPoints)eeex"},
        FieldDesc{0x4C9C, 4, R"eeex(int)eeex", R"eeex(m_moraleFailure)eeex"},
        FieldDesc{0x4CA0, 4, R"eeex(int)eeex", R"eeex(m_startedSwing)eeex"},
        FieldDesc{0x4CA4, 2, R"eeex(__int16)eeex", R"eeex(m_followCount)eeex"},
        FieldDesc{0x4CA8, 4, R"eeex(int)eeex", R"eeex(m_clearAIOnRemoveFromArea)eeex"},
        FieldDesc{0x4CAC, 4, R"eeex(int)eeex", R"eeex(m_dialogWait)eeex"},
        FieldDesc{0x4CB0, 4, R"eeex(int)eeex", R"eeex(m_dialogWaitTarget)eeex"},
        FieldDesc{0x4CB4, 4, R"eeex(int)eeex", R"eeex(m_talkingCounter)eeex"},
        FieldDesc{0x4CB8, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_talkingRenderCount)eeex"},
        FieldDesc{0x4CB9, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_inControlLastTime)eeex"},
        FieldDesc{0x4CBA, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_bSecondPass)eeex"},
        FieldDesc{0x4CC0, 56, R"eeex(:ref:`CTypedPtrList<CTypedPtrList>`\<:ref:`CPtrList<CPtrList>`, :ref:`CPortraitIcon<CPortraitIcon>`\*>)eeex", R"eeex(m_portraitIcons)eeex"},
        FieldDesc{0x4CF8, 312, R"eeex(:ref:`CVidCell<CVidCell>`)eeex", R"eeex(m_portraitIconVidCell)eeex"},
        FieldDesc{0x4E30, 4, R"eeex(int)eeex", R"eeex(m_firstActionSound)eeex"},
        FieldDesc{0x4E34, 4, R"eeex(int)eeex", R"eeex(m_lastRested)eeex"},
        FieldDesc{0x4E38, 4, R"eeex(int)eeex", R"eeex(m_berserkActive)eeex"},
        FieldDesc{0x4E3C, 2, R"eeex(__int16)eeex", R"eeex(m_attackSoundDeadzone)eeex"},
        FieldDesc{0x4E40, 4, R"eeex(int)eeex", R"eeex(m_nHPCONBonusTotalOld)eeex"},
        FieldDesc{0x4E44, 4, R"eeex(int)eeex", R"eeex(m_bHPCONBonusTotalUpdate)eeex"},
        FieldDesc{0x4E48, 4, R"eeex(int)eeex", R"eeex(m_nLastWeightCheck)eeex"},
        FieldDesc{0x4E4C, 4, R"eeex(unsigned int)eeex", R"eeex(m_modalCounter)eeex"},
        FieldDesc{0x4E50, 4, R"eeex(int)eeex", R"eeex(m_bHiding)eeex"},
        FieldDesc{0x4E54, 4, R"eeex(unsigned int)eeex", R"eeex(m_lastRegenerationTime)eeex"},
        FieldDesc{0x4E58, 4, R"eeex(int)eeex", R"eeex(m_bLevelUp)eeex"},
        FieldDesc{0x4E5C, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_bAllowDialogInterrupt)eeex"},
        FieldDesc{0x4E5D, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_bHappinessChanged)eeex"},
        FieldDesc{0x4E60, 4, R"eeex(int)eeex", R"eeex(m_nUnselectableCounter)eeex"},
        FieldDesc{0x4E64, 4, R"eeex(unsigned int)eeex", R"eeex(m_nUnselectableType)eeex"},
        FieldDesc{0x4E68, 8, R"eeex(:ref:`CResRef<CResRef>`)eeex", R"eeex(m_secondarySounds)eeex"},
        FieldDesc{0x4E70, 4, R"eeex(int)eeex", R"eeex(m_nStealthGreyOut)eeex"},
        FieldDesc{0x4E74, 4, R"eeex(int)eeex", R"eeex(m_bMentalStateActing)eeex"},
        FieldDesc{0x4E78, 12, R"eeex(Array<int,3>)eeex", R"eeex(m_nLastLevelUpLevel)eeex"},
        FieldDesc{0x4E84, 4, R"eeex(int)eeex", R"eeex(m_nLastLevelUpHPRoll)eeex"},
        FieldDesc{0x4E88, 4, R"eeex(int)eeex", R"eeex(m_bForceVisualEffects)eeex"},
        FieldDesc{0x4E8C, 2, R"eeex(__int16)eeex", R"eeex(m_currentActionId)eeex"},
        FieldDesc{0x4E90, 4, R"eeex(int)eeex", R"eeex(m_bPlayedEncumberedStopped)eeex"},
        FieldDesc{0x4E94, 4, R"eeex(int)eeex", R"eeex(m_bPlayedEncumberedSlowed)eeex"},
        FieldDesc{0x4E98, 4, R"eeex(int)eeex", R"eeex(m_nPlayedEncumberedStopped)eeex"},
        FieldDesc{0x4E9C, 4, R"eeex(int)eeex", R"eeex(m_nPlayedEncumberedSlowed)eeex"},
        FieldDesc{0x4EA0, 2, R"eeex(__int16)eeex", R"eeex(m_nPlayedPoisonedDamage)eeex"},
        FieldDesc{0x4EA2, 2, R"eeex(__int16)eeex", R"eeex(m_nEffectListCalls)eeex"},
        FieldDesc{0x4EA4, 4, R"eeex(int)eeex", R"eeex(m_bAllowEffectListCall)eeex"},
        FieldDesc{0x4EA8, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_nPreCutSceneMoveScale)eeex"},
        FieldDesc{0x4EAC, 4, R"eeex(int)eeex", R"eeex(m_bUsingCutSceneMovement)eeex"},
        FieldDesc{0x4EB0, 4, R"eeex(int)eeex", R"eeex(m_bDeleteOnRemove)eeex"},
        FieldDesc{0x4EB8, 8, R"eeex(:ref:`CVariableHash<CVariableHash>`\*)eeex", R"eeex(m_pLocalVariables)eeex"},
        FieldDesc{0x4EC0, 4, R"eeex(int)eeex", R"eeex(m_bInUnmarshal)eeex"},
        FieldDesc{0x4EC8, 56, R"eeex(:ref:`CBounceList<CBounceList>`)eeex", R"eeex(m_lBounceList)eeex"},
        FieldDesc{0x4F00, 4, R"eeex(int)eeex", R"eeex(m_nTransitionPointIndex)eeex"},
        FieldDesc{0x4F04, 4, R"eeex(int)eeex", R"eeex(m_nBounceCounter)eeex"},
        FieldDesc{0x4F08, 4, R"eeex(int)eeex", R"eeex(m_nMoraleAI)eeex"},
        FieldDesc{0x4F0C, 4, R"eeex(int)eeex", R"eeex(m_nGeneratedVEFIndex)eeex"},
        FieldDesc{0x4F10, 4, R"eeex(int)eeex", R"eeex(m_nTrackingCounter)eeex"},
        FieldDesc{0x4F18, 8, R"eeex(:ref:`CGameButtonList<CGameButtonList>`\*)eeex", R"eeex(m_interalButtonList)eeex"},
        FieldDesc{0x4F20, 8, R"eeex(:ref:`CAIScript<CAIScript>`\*)eeex", R"eeex(m_dreamScript)eeex"},
        FieldDesc{0x4F28, 136, R"eeex(:ref:`CGameDialogSprite<CGameDialogSprite>`)eeex", R"eeex(m_cDialog)eeex"},
        FieldDesc{0x4FB0, 136, R"eeex(:ref:`CGameDialogSprite<CGameDialogSprite>`)eeex", R"eeex(m_cBanter)eeex"},
        FieldDesc{0x5038, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_bForceVisRangeRedraw)eeex"},
        FieldDesc{0x503C, 4, R"eeex(int)eeex", R"eeex(m_nLastExpiryCheck)eeex"},
        FieldDesc{0x5040, 4, R"eeex(int)eeex", R"eeex(m_nLastContingencyCheck)eeex"},
        FieldDesc{0x5048, 8, R"eeex(:ref:`CString<CString>`)eeex", R"eeex(m_hitBonusesLeft)eeex"},
        FieldDesc{0x5050, 8, R"eeex(:ref:`CString<CString>`)eeex", R"eeex(m_hitBonusesRight)eeex"},
        FieldDesc{0x5058, 8, R"eeex(:ref:`CString<CString>`)eeex", R"eeex(m_damageBonusesLeft)eeex"},
        FieldDesc{0x5060, 8, R"eeex(:ref:`CString<CString>`)eeex", R"eeex(m_damageBonusesRight)eeex"},
        FieldDesc{0x5068, 2, R"eeex(__int16)eeex", R"eeex(m_effectMovementRate)eeex"},
        FieldDesc{0x506C, 4, R"eeex(unsigned int)eeex", R"eeex(m_effectStateFlags)eeex"},
        FieldDesc{0x5070, 144, R"eeex(Array<:ref:`CCreatureFileMemorizedSpellLevel<CCreatureFileMemorizedSpellLevel>`,9>)eeex", R"eeex(m_effectMemorizedSpellsLevelMage)eeex"},
        FieldDesc{0x5100, 112, R"eeex(Array<:ref:`CCreatureFileMemorizedSpellLevel<CCreatureFileMemorizedSpellLevel>`,7>)eeex", R"eeex(m_effectMemorizedSpellsLevelPriest)eeex"},
        FieldDesc{0x5170, 4, R"eeex(int)eeex", R"eeex(m_effectStoreInitialized)eeex"},
        FieldDesc{0x5174, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_nLevellingUp)eeex"},
        FieldDesc{0x5178, 4, R"eeex(int)eeex", R"eeex(m_bHasDeathSequence)eeex"},
        FieldDesc{0x5180, 56, R"eeex(:ref:`CTypedPtrList<CTypedPtrList>`\<:ref:`CPtrList<CPtrList>`,long*>)eeex", R"eeex(m_lstTargetIds)eeex"},
        FieldDesc{0x51B8, 56, R"eeex(:ref:`CTypedPtrList<CTypedPtrList>`\<:ref:`CPtrList<CPtrList>`, :ref:`CPoint<CPoint>`\*>)eeex", R"eeex(m_lstTargetPts)eeex"},
        FieldDesc{0x51F0, 4, R"eeex(int)eeex", R"eeex(m_bInStoreState)eeex"},
        FieldDesc{0x51F4, 4, R"eeex(int)eeex", R"eeex(m_bInDialogState)eeex"},
        FieldDesc{0x51F8, 4, R"eeex(int)eeex", R"eeex(m_nDialogState)eeex"},
        FieldDesc{0x51FC, 4, R"eeex(int)eeex", R"eeex(m_nWaitingOnDialog)eeex"},
        FieldDesc{0x5200, 1, R"eeex(bool)eeex", R"eeex(m_bHighlightPortrait)eeex"},
        FieldDesc{0x5204, 4, R"eeex(unsigned int)eeex", R"eeex(m_nHighlightColor)eeex"},
        FieldDesc{0x5208, 4, R"eeex(int)eeex", R"eeex(m_bCutSceneOverrideOfState)eeex"},
        FieldDesc{0x520C, 4, R"eeex(int)eeex", R"eeex(m_bForceEffectProcessFromTimeStop)eeex"},
        FieldDesc{0x5210, 4, R"eeex(int)eeex", R"eeex(m_bCopyForAdd)eeex"},
        FieldDesc{0x5214, 4, R"eeex(int)eeex", R"eeex(m_nCopyParent)eeex"},
        FieldDesc{0x5218, 56, R"eeex(:ref:`CTypedPtrList<CTypedPtrList>`\<:ref:`CPtrList<CPtrList>`, :ref:`CFeedbackEntry<CFeedbackEntry>`\*>)eeex", R"eeex(m_feedbackQueue)eeex"},
        FieldDesc{0x5250, 4, R"eeex(int)eeex", R"eeex(m_bOnSearchMap)eeex"},
        FieldDesc{0x5254, 4, R"eeex(int)eeex", R"eeex(m_bRemovedFromMap)eeex"},
        FieldDesc{0x5258, 136, R"eeex(:ref:`CGameSpriteLastUpdate<CGameSpriteLastUpdate>`)eeex", R"eeex(m_cLastSpriteUpdate)eeex"},
        FieldDesc{0x52E0, 4, R"eeex(int)eeex", R"eeex(m_bSendSpriteUpdate)eeex"},
        FieldDesc{0x52E4, 4, R"eeex(int)eeex", R"eeex(m_nLastDamageTaken)eeex"},
        FieldDesc{0x52E8, 4, R"eeex(int)eeex", R"eeex(m_nDeadVisualEffectCountDown)eeex"},
        FieldDesc{0x52EC, 4, R"eeex(int)eeex", R"eeex(m_bForceVisibilityCheck)eeex"},
        FieldDesc{0x52F0, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_nVisualRange)eeex"},
        FieldDesc{0x52F4, 4, R"eeex(int)eeex", R"eeex(m_bPlayAnimationBattleCry)eeex"},
        FieldDesc{0x52F8, 4, R"eeex(int)eeex", R"eeex(m_bPlayAnimationSelectionSound)eeex"},
        FieldDesc{0x52FC, 10, R"eeex(Array<unsigned __int8,10>)eeex", R"eeex(m_aLevellupSpellsToPick)eeex"},
        FieldDesc{0x5308, 4, R"eeex(int)eeex", R"eeex(m_nCrossAreaChaseCounter)eeex"},
        FieldDesc{0x530C, 4, R"eeex(int)eeex", R"eeex(m_bDidAReequipAll)eeex"},
        FieldDesc{0x5310, 4, R"eeex(int)eeex", R"eeex(m_bInEquip)eeex"},
        FieldDesc{0x5314, 1, R"eeex(char)eeex", R"eeex(m_cFirstResSlot)eeex"},
        FieldDesc{0x5318, 4, R"eeex(int)eeex", R"eeex(m_nNumColorRanges)eeex"},
        FieldDesc{0x531C, 4, R"eeex(int)eeex", R"eeex(m_nNumColorEffects)eeex"},
        FieldDesc{0x5320, 4, R"eeex(int)eeex", R"eeex(m_nNumWeaponImmunities)eeex"},
        FieldDesc{0x5324, 4, R"eeex(int)eeex", R"eeex(m_bCheckedIfVisiblePause)eeex"},
        FieldDesc{0x5328, 4, R"eeex(int)eeex", R"eeex(m_bCheckedSpecialAbilities)eeex"},
        FieldDesc{0x532C, 4, R"eeex(int)eeex", R"eeex(m_bDroppedTempItem)eeex"},
        FieldDesc{0x5330, 4, R"eeex(int)eeex", R"eeex(m_nSkippedUpdates)eeex"},
        FieldDesc{0x5334, 4, R"eeex(int)eeex", R"eeex(m_bDelayUpdate)eeex"},
        FieldDesc{0x5338, 4, R"eeex(int)eeex", R"eeex(m_nHalfSwingCounter)eeex"},
        FieldDesc{0x533C, 1, R"eeex(bool)eeex", R"eeex(m_bInCopy)eeex"},
        FieldDesc{0x5340, 56, R"eeex(:ref:`CTypedPtrList<CTypedPtrList>`\<:ref:`CPtrList<CPtrList>`, :ref:`CGameSprite::GroundItem<CGameSprite::GroundItem>`\*>)eeex", R"eeex(m_lstVisibleGroundItems)eeex"},
        FieldDesc{0x5378, 4, R"eeex(int)eeex", R"eeex(m_nGroundItemPage)eeex"},
        FieldDesc{0x537C, 4, R"eeex(float)eeex", R"eeex(m_avgProcessAITime)eeex"},
        FieldDesc{0x5380, 4, R"eeex(int)eeex", R"eeex(m_nMaxHitPointsOnceOnlyBonus)eeex"},
        FieldDesc{0x5384, 1, R"eeex(bool)eeex", R"eeex(m_bOutline)eeex"},
    }};
    inline constexpr LayoutDesc CGameSpriteLayout{0x5388, static_cast<std::uint32_t>(CGameSpriteFields.size())};

    inline constexpr std::array<FieldDesc, 24> CGameAnimationTypeFields{{
        FieldDesc{0x0, 8, R"eeex(qword)eeex", R"eeex(vfptr)eeex"},
        FieldDesc{0x8, 2, R"eeex(unsigned __int16)eeex", R"eeex(m_animationID)eeex"},
        FieldDesc{0xA, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_moveScale)eeex"},
        FieldDesc{0xB, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_moveScaleCurrent)eeex"},
        FieldDesc{0xC, 16, R"eeex(:ref:`CRect<CRect>`)eeex", R"eeex(m_rEllipse)eeex"},
        FieldDesc{0x1C, 4, R"eeex(int)eeex", R"eeex(m_nHeightOffset)eeex"},
        FieldDesc{0x20, 1, R"eeex(bool)eeex", R"eeex(m_bUseSpriteShader)eeex"},
        FieldDesc{0x21, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_colorBlood)eeex"},
        FieldDesc{0x22, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_colorChunks)eeex"},
        FieldDesc{0x24, 4, R"eeex(unsigned int)eeex", R"eeex(m_nSndFreq)eeex"},
        FieldDesc{0x28, 8, R"eeex(const char*)eeex", R"eeex(m_pSndDeath)eeex"},
        FieldDesc{0x30, 32, R"eeex(Array<NECK_POINTS,8>)eeex", R"eeex(m_neckOffsets)eeex"},
        FieldDesc{0x50, 1440, R"eeex(Array<:ref:`CVidBitmap<CVidBitmap>`,5>)eeex", R"eeex(m_combatRounds)eeex"},
        FieldDesc{0x5F0, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_personalSpace)eeex"},
        FieldDesc{0x5F1, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_walkCount)eeex"},
        FieldDesc{0x5F2, 2, R"eeex(unsigned __int16)eeex", R"eeex(m_castFrame)eeex"},
        FieldDesc{0x5F4, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_bBrightest)eeex"},
        FieldDesc{0x5F5, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_bBrightestDesired)eeex"},
        FieldDesc{0x5F6, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_bLightSource)eeex"},
        FieldDesc{0x5F7, 8, R"eeex(:ref:`CResRef<CResRef>`)eeex", R"eeex(m_soundRef)eeex"},
        FieldDesc{0x600, 8, R"eeex(:ref:`CString<CString>`)eeex", R"eeex(m_walkRef)eeex"},
        FieldDesc{0x608, 1440, R"eeex(Array<:ref:`CSequenceSoundList<CSequenceSoundList>`,20>)eeex", R"eeex(m_sequenceRefs)eeex"},
        FieldDesc{0xBA8, 4, R"eeex(int)eeex", R"eeex(m_bNewPalette)eeex"},
        FieldDesc{0xBB0, 288, R"eeex(:ref:`CVidBitmap<CVidBitmap>`)eeex", R"eeex(m_newPalette)eeex"},
    }};
    inline constexpr LayoutDesc CGameAnimationTypeLayout{0xCD0, static_cast<std::uint32_t>(CGameAnimationTypeFields.size())};

    inline constexpr std::array<FieldDesc, 153> CGameOptionsFields{{
        FieldDesc{0x0, 4, R"eeex(unsigned int)eeex", R"eeex(m_gore)eeex"},
        FieldDesc{0x4, 4, R"eeex(unsigned int)eeex", R"eeex(m_goreOption)eeex"},
        FieldDesc{0x8, 4, R"eeex(unsigned int)eeex", R"eeex(m_scrollSpeed)eeex"},
        FieldDesc{0xC, 4, R"eeex(unsigned int)eeex", R"eeex(m_displayVerbalText)eeex"},
        FieldDesc{0x10, 4, R"eeex(unsigned int)eeex", R"eeex(m_guiFeedBackLevel)eeex"},
        FieldDesc{0x14, 4, R"eeex(unsigned int)eeex", R"eeex(m_locatorFeedBackLevel)eeex"},
        FieldDesc{0x18, 4, R"eeex(unsigned int)eeex", R"eeex(m_soundMusicVolume)eeex"},
        FieldDesc{0x1C, 4, R"eeex(unsigned int)eeex", R"eeex(m_soundFXVolume)eeex"},
        FieldDesc{0x20, 4, R"eeex(unsigned int)eeex", R"eeex(m_soundDialogVolume)eeex"},
        FieldDesc{0x24, 4, R"eeex(unsigned int)eeex", R"eeex(m_nVolumeAmbients)eeex"},
        FieldDesc{0x28, 4, R"eeex(unsigned int)eeex", R"eeex(m_soundMovieVolume)eeex"},
        FieldDesc{0x2C, 4, R"eeex(unsigned int)eeex", R"eeex(m_soundFootStepsOn)eeex"},
        FieldDesc{0x30, 4, R"eeex(unsigned int)eeex", R"eeex(m_soundVoicesNo)eeex"},
        FieldDesc{0x34, 4, R"eeex(unsigned int)eeex", R"eeex(m_graphicsBrightness)eeex"},
        FieldDesc{0x38, 4, R"eeex(unsigned int)eeex", R"eeex(m_graphicsFontZoom)eeex"},
        FieldDesc{0x3C, 4, R"eeex(float)eeex", R"eeex(m_spriteBlurAmount)eeex"},
        FieldDesc{0x40, 4, R"eeex(unsigned int)eeex", R"eeex(m_graphicsTranslucentShadows)eeex"},
        FieldDesc{0x44, 4, R"eeex(unsigned int)eeex", R"eeex(m_graphicsForceMirroringOff)eeex"},
        FieldDesc{0x48, 4, R"eeex(unsigned int)eeex", R"eeex(m_graphicsTranslucentEffects)eeex"},
        FieldDesc{0x4C, 4, R"eeex(unsigned int)eeex", R"eeex(m_toolTips)eeex"},
        FieldDesc{0x50, 4, R"eeex(unsigned int)eeex", R"eeex(m_nBoredTime)eeex"},
        FieldDesc{0x54, 4, R"eeex(unsigned int)eeex", R"eeex(m_nCommandSoundsFrequency)eeex"},
        FieldDesc{0x58, 4, R"eeex(unsigned int)eeex", R"eeex(m_nSelectionSoundsFrequency)eeex"},
        FieldDesc{0x5C, 4, R"eeex(unsigned int)eeex", R"eeex(m_bAlwaysDither)eeex"},
        FieldDesc{0x60, 4, R"eeex(unsigned int)eeex", R"eeex(m_nKeyBoardScrollAmount)eeex"},
        FieldDesc{0x64, 4, R"eeex(unsigned int)eeex", R"eeex(m_nEffectTextLevel)eeex"},
        FieldDesc{0x68, 4, R"eeex(unsigned int)eeex", R"eeex(m_nTutorialState)eeex"},
        FieldDesc{0x6C, 4, R"eeex(unsigned int)eeex", R"eeex(m_nAttackSounds)eeex"},
        FieldDesc{0x70, 4, R"eeex(unsigned int)eeex", R"eeex(m_nAutoPauseState)eeex"},
        FieldDesc{0x74, 4, R"eeex(unsigned int)eeex", R"eeex(m_bAutoPauseCenter)eeex"},
        FieldDesc{0x78, 4, R"eeex(int)eeex", R"eeex(m_nDifficultyMultiplier)eeex"},
        FieldDesc{0x7C, 4, R"eeex(int)eeex", R"eeex(m_nMPDifficultyMultiplier)eeex"},
        FieldDesc{0x80, 4, R"eeex(int)eeex", R"eeex(m_bNoExtraDamage)eeex"},
        FieldDesc{0x84, 4, R"eeex(int)eeex", R"eeex(m_bAutoUseMagicAmmo)eeex"},
        FieldDesc{0x88, 4, R"eeex(int)eeex", R"eeex(m_bNoExtraXP)eeex"},
        FieldDesc{0x8C, 4, R"eeex(unsigned int)eeex", R"eeex(m_bInfravision)eeex"},
        FieldDesc{0x90, 4, R"eeex(unsigned int)eeex", R"eeex(m_bStupidQuickItemStuff)eeex"},
        FieldDesc{0x94, 4, R"eeex(int)eeex", R"eeex(m_bWeatherEnabled)eeex"},
        FieldDesc{0x98, 4, R"eeex(int)eeex", R"eeex(m_bCheatsEnabled)eeex"},
        FieldDesc{0x9C, 4, R"eeex(int)eeex", R"eeex(m_bEnvironmentalAudio)eeex"},
        FieldDesc{0xA0, 4, R"eeex(int)eeex", R"eeex(m_bRestHealParty)eeex"},
        FieldDesc{0xA4, 4, R"eeex(int)eeex", R"eeex(m_bTerrainHugging)eeex"},
        FieldDesc{0xA8, 4, R"eeex(int)eeex", R"eeex(m_bHPOverHead)eeex"},
        FieldDesc{0xAC, 4, R"eeex(int)eeex", R"eeex(m_bDebugMode)eeex"},
        FieldDesc{0xB0, 4, R"eeex(int)eeex", R"eeex(m_bUIEditMode)eeex"},
        FieldDesc{0xB4, 4, R"eeex(int)eeex", R"eeex(m_bCloudSavesEnabled)eeex"},
        FieldDesc{0xB8, 4, R"eeex(int)eeex", R"eeex(m_bNeverShowNuisanceSOD)eeex"},
        FieldDesc{0xBC, 4, R"eeex(int)eeex", R"eeex(m_nActiveCampaign)eeex"},
        FieldDesc{0xC0, 4, R"eeex(int)eeex", R"eeex(m_bDeveloperMode)eeex"},
        FieldDesc{0xC4, 4, R"eeex(int)eeex", R"eeex(m_bForceDialogPause)eeex"},
        FieldDesc{0xC8, 4, R"eeex(int)eeex", R"eeex(m_bUse3dAnimations)eeex"},
        FieldDesc{0xCC, 4, R"eeex(int)eeex", R"eeex(m_bCriticalHitScreenShake)eeex"},
        FieldDesc{0xD0, 4, R"eeex(int)eeex", R"eeex(m_bHotkeysOnToolTips)eeex"},
        FieldDesc{0xD4, 4, R"eeex(int)eeex", R"eeex(m_bVeryLowPerformance)eeex"},
        FieldDesc{0xD8, 4, R"eeex(int)eeex", R"eeex(m_bDisplayExtraCombatInfo)eeex"},
        FieldDesc{0xDC, 2, R"eeex(unsigned __int16)eeex", R"eeex(m_nAreaEffectsDensity)eeex"},
        FieldDesc{0xE0, 4, R"eeex(int)eeex", R"eeex(m_bDuplicateFloatingText)eeex"},
        FieldDesc{0xE4, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_nTilesPrecachePercent)eeex"},
        FieldDesc{0xE8, 4, R"eeex(int)eeex", R"eeex(m_bColorCircles)eeex"},
        FieldDesc{0xEC, 4, R"eeex(int)eeex", R"eeex(m_bClassicCircles)eeex"},
        FieldDesc{0xF0, 4, R"eeex(int)eeex", R"eeex(m_nCombatUI)eeex"},
        FieldDesc{0xF4, 4, R"eeex(int)eeex", R"eeex(m_bOverConfirmEverything)eeex"},
        FieldDesc{0xF8, 4, R"eeex(int)eeex", R"eeex(m_bShowLearnableSpells)eeex"},
        FieldDesc{0xFC, 4, R"eeex(int)eeex", R"eeex(m_bShowTriggersOnTab)eeex"},
        FieldDesc{0x100, 4, R"eeex(int)eeex", R"eeex(m_bShowBlackSpace)eeex"},
        FieldDesc{0x104, 4, R"eeex(int)eeex", R"eeex(m_bUseNearestNeighbourScaling)eeex"},
        FieldDesc{0x108, 4, R"eeex(int)eeex", R"eeex(m_showAOE)eeex"},
        FieldDesc{0x10C, 4, R"eeex(int)eeex", R"eeex(m_bEquipmentComparison)eeex"},
        FieldDesc{0x110, 4, R"eeex(int)eeex", R"eeex(m_bDisableCastingGlows)eeex"},
        FieldDesc{0x114, 4, R"eeex(int)eeex", R"eeex(m_bLowMemSounds1)eeex"},
        FieldDesc{0x118, 4, R"eeex(int)eeex", R"eeex(m_bLowMemSounds2)eeex"},
        FieldDesc{0x11C, 4, R"eeex(int)eeex", R"eeex(m_bDisableVEFVidCells)eeex"},
        FieldDesc{0x120, 4, R"eeex(int)eeex", R"eeex(m_bDisableDisplayText)eeex"},
        FieldDesc{0x124, 4, R"eeex(int)eeex", R"eeex(m_bMidLevelBrighten)eeex"},
        FieldDesc{0x128, 4, R"eeex(int)eeex", R"eeex(m_bHighLevelBrighten)eeex"},
        FieldDesc{0x12C, 2, R"eeex(unsigned __int16)eeex", R"eeex(m_nAreaEffectsRefreshProb)eeex"},
        FieldDesc{0x130, 4, R"eeex(int)eeex", R"eeex(m_bEnhancedPathSearch)eeex"},
        FieldDesc{0x134, 4, R"eeex(int)eeex", R"eeex(m_bPausingMap)eeex"},
        FieldDesc{0x138, 4, R"eeex(int)eeex", R"eeex(m_bExtraFeedback)eeex"},
        FieldDesc{0x13C, 4, R"eeex(int)eeex", R"eeex(m_bFilterGames)eeex"},
        FieldDesc{0x140, 4, R"eeex(int)eeex", R"eeex(m_bAllLearnSpellInfo)eeex"},
        FieldDesc{0x144, 4, R"eeex(int)eeex", R"eeex(m_bDisableStaticsDuringCombat)eeex"},
        FieldDesc{0x148, 4, R"eeex(int)eeex", R"eeex(m_bDisableFootstepsDuringCombat)eeex"},
        FieldDesc{0x14C, 4, R"eeex(int)eeex", R"eeex(m_bDisablePlacedSoundsDuringCombat)eeex"},
        FieldDesc{0x150, 4, R"eeex(int)eeex", R"eeex(m_nSuperDesperateSpeedAttempt)eeex"},
        FieldDesc{0x154, 4, R"eeex(int)eeex", R"eeex(m_bAutomatedSpeedAdjusting)eeex"},
        FieldDesc{0x158, 4, R"eeex(int)eeex", R"eeex(m_bAutomatedGraphicsTranslucentShadows)eeex"},
        FieldDesc{0x15C, 4, R"eeex(int)eeex", R"eeex(m_bAutomatedVeryLowPerformance)eeex"},
        FieldDesc{0x160, 4, R"eeex(int)eeex", R"eeex(m_bAutomatedLowPerformance)eeex"},
        FieldDesc{0x164, 4, R"eeex(int)eeex", R"eeex(m_bAutomatedDisableBrightest)eeex"},
        FieldDesc{0x168, 4, R"eeex(int)eeex", R"eeex(m_bAutomatedLimitTransparency)eeex"},
        FieldDesc{0x16C, 4, R"eeex(int)eeex", R"eeex(m_bAutomatedDisableCastingGlows)eeex"},
        FieldDesc{0x170, 4, R"eeex(int)eeex", R"eeex(m_bAutomatedDisableVEFVidCells)eeex"},
        FieldDesc{0x174, 4, R"eeex(int)eeex", R"eeex(m_bAutomatedMidLevelBrighten)eeex"},
        FieldDesc{0x178, 4, R"eeex(int)eeex", R"eeex(m_bAutomatedHighLevelBrighten)eeex"},
        FieldDesc{0x17C, 4, R"eeex(int)eeex", R"eeex(m_bAutomatedSoundFootStepsOn)eeex"},
        FieldDesc{0x180, 4, R"eeex(int)eeex", R"eeex(m_bAutomatedAttackSounds)eeex"},
        FieldDesc{0x184, 4, R"eeex(int)eeex", R"eeex(m_bAutomatedUse3dAnimations)eeex"},
        FieldDesc{0x188, 4, R"eeex(int)eeex", R"eeex(m_bAutomatedDisableVVCSounds)eeex"},
        FieldDesc{0x18C, 4, R"eeex(int)eeex", R"eeex(m_bAutomatedFasterBlur)eeex"},
        FieldDesc{0x190, 4, R"eeex(int)eeex", R"eeex(m_nCutAutomatedGraphicsTranslucentShadows)eeex"},
        FieldDesc{0x194, 4, R"eeex(int)eeex", R"eeex(m_nCutAutomatedVeryLowPerformance)eeex"},
        FieldDesc{0x198, 4, R"eeex(int)eeex", R"eeex(m_nCutAutomatedLowPerformance)eeex"},
        FieldDesc{0x19C, 4, R"eeex(int)eeex", R"eeex(m_nCutAutomatedDisableBrightest)eeex"},
        FieldDesc{0x1A0, 4, R"eeex(int)eeex", R"eeex(m_nCutAutomatedLimitTransparency)eeex"},
        FieldDesc{0x1A4, 4, R"eeex(int)eeex", R"eeex(m_nCutAutomatedDisableCastingGlows)eeex"},
        FieldDesc{0x1A8, 4, R"eeex(int)eeex", R"eeex(m_nCutAutomatedDisableVEFVidCells)eeex"},
        FieldDesc{0x1AC, 4, R"eeex(int)eeex", R"eeex(m_nCutAutomatedMidLevelBrighten)eeex"},
        FieldDesc{0x1B0, 4, R"eeex(int)eeex", R"eeex(m_nCutAutomatedHighLevelBrighten)eeex"},
        FieldDesc{0x1B4, 4, R"eeex(int)eeex", R"eeex(m_nCutAutomatedSoundFootStepsOn)eeex"},
        FieldDesc{0x1B8, 4, R"eeex(int)eeex", R"eeex(m_nCutAutomatedAttackSounds)eeex"},
        FieldDesc{0x1BC, 4, R"eeex(int)eeex", R"eeex(m_nCutAutomatedUse3dAnimations)eeex"},
        FieldDesc{0x1C0, 4, R"eeex(int)eeex", R"eeex(m_nCutAutomatedDisableVVCSounds)eeex"},
        FieldDesc{0x1C4, 4, R"eeex(int)eeex", R"eeex(m_nCutAutomatedFasterBlur)eeex"},
        FieldDesc{0x1C8, 4, R"eeex(int)eeex", R"eeex(m_bPCOnlyCombatMode)eeex"},
        FieldDesc{0x1CC, 4, R"eeex(int)eeex", R"eeex(m_bFullyDisableNonVisibleDuringCombat)eeex"},
        FieldDesc{0x1D0, 4, R"eeex(int)eeex", R"eeex(m_bDisableVVCSounds)eeex"},
        FieldDesc{0x1D4, 4, R"eeex(int)eeex", R"eeex(m_bFasterBlur)eeex"},
        FieldDesc{0x1D8, 4, R"eeex(int)eeex", R"eeex(m_nFatFingerRadius)eeex"},
        FieldDesc{0x1DC, 4, R"eeex(int)eeex", R"eeex(m_bScaleUI)eeex"},
        FieldDesc{0x1E0, 4, R"eeex(int)eeex", R"eeex(m_nRenderActionQueue)eeex"},
        FieldDesc{0x1E4, 4, R"eeex(int)eeex", R"eeex(m_bConfirmDialog)eeex"},
        FieldDesc{0x1E8, 4, R"eeex(int)eeex", R"eeex(m_bHardwareMouseCursor)eeex"},
        FieldDesc{0x1EC, 4, R"eeex(int)eeex", R"eeex(m_bShowHealth)eeex"},
        FieldDesc{0x1F0, 4, R"eeex(int)eeex", R"eeex(m_bMaxHP)eeex"},
        FieldDesc{0x1F4, 4, R"eeex(int)eeex", R"eeex(m_bStoryMode)eeex"},
        FieldDesc{0x1F8, 4, R"eeex(int)eeex", R"eeex(m_bNightmareMode)eeex"},
        FieldDesc{0x1FC, 4, R"eeex(int)eeex", R"eeex(m_bNightmareBonusGold)eeex"},
        FieldDesc{0x200, 4, R"eeex(int)eeex", R"eeex(m_bNightmareBonusXP)eeex"},
        FieldDesc{0x204, 4, R"eeex(int)eeex", R"eeex(m_b3ESneakAttack)eeex"},
        FieldDesc{0x208, 4, R"eeex(int)eeex", R"eeex(m_bClericRangerFix)eeex"},
        FieldDesc{0x20C, 4, R"eeex(int)eeex", R"eeex(m_bShowPauseDate)eeex"},
        FieldDesc{0x210, 4, R"eeex(int)eeex", R"eeex(m_bDisableCosmeticAttacks)eeex"},
        FieldDesc{0x214, 4, R"eeex(int)eeex", R"eeex(m_bJournalPopups)eeex"},
        FieldDesc{0x218, 4, R"eeex(int)eeex", R"eeex(m_bRenderTravelRegions)eeex"},
        FieldDesc{0x21C, 4, R"eeex(int)eeex", R"eeex(m_bRenderSearchMap)eeex"},
        FieldDesc{0x220, 4, R"eeex(int)eeex", R"eeex(m_bRenderDynamicSearchMap)eeex"},
        FieldDesc{0x224, 4, R"eeex(int)eeex", R"eeex(m_bRenderFrameTimes)eeex"},
        FieldDesc{0x228, 4, R"eeex(int)eeex", R"eeex(m_bZoomLock)eeex"},
        FieldDesc{0x22C, 4, R"eeex(int)eeex", R"eeex(m_bDisableMultiplayerBanters)eeex"},
        FieldDesc{0x230, 4, R"eeex(int)eeex", R"eeex(m_bRenderPath)eeex"},
        FieldDesc{0x234, 4, R"eeex(int)eeex", R"eeex(m_bFogEnabled)eeex"},
        FieldDesc{0x238, 4, R"eeex(int)eeex", R"eeex(m_bUseSpriteShader)eeex"},
        FieldDesc{0x23C, 4, R"eeex(int)eeex", R"eeex(m_bCharacterHighlightsEnabled)eeex"},
        FieldDesc{0x240, 4, R"eeex(int)eeex", R"eeex(m_bGreyscaleOnPauseEnabled)eeex"},
        FieldDesc{0x244, 4, R"eeex(int)eeex", R"eeex(m_bShortDescription)eeex"},
        FieldDesc{0x248, 4, R"eeex(int)eeex", R"eeex(m_nMaxStringEntries)eeex"},
        FieldDesc{0x24C, 4, R"eeex(int)eeex", R"eeex(m_bRenderExploredMap)eeex"},
        FieldDesc{0x250, 4, R"eeex(int)eeex", R"eeex(m_bEnableDirectX)eeex"},
        FieldDesc{0x254, 4, R"eeex(int)eeex", R"eeex(m_bEnableMPChatMenu)eeex"},
        FieldDesc{0x258, 4, R"eeex(int)eeex", R"eeex(m_bExpireTraps)eeex"},
        FieldDesc{0x25C, 4, R"eeex(int)eeex", R"eeex(m_bAreaMapZoom)eeex"},
        FieldDesc{0x260, 4, R"eeex(int)eeex", R"eeex(m_nDifficultyLevel)eeex"},
    }};
    inline constexpr LayoutDesc CGameOptionsLayout{0x264, static_cast<std::uint32_t>(CGameOptionsFields.size())};

    inline constexpr std::array<FieldDesc, 42> CVidModeFields{{
        FieldDesc{0x0, 4, R"eeex(int)eeex", R"eeex(m_nPrintFile)eeex"},
        FieldDesc{0x4, 4, R"eeex(int)eeex", R"eeex(m_nPointerNumber)eeex"},
        FieldDesc{0x8, 4, R"eeex(unsigned int)eeex", R"eeex(m_dwCursorRenderFlags)eeex"},
        FieldDesc{0xC, 4, R"eeex(unsigned int)eeex", R"eeex(m_dwRedMask)eeex"},
        FieldDesc{0x10, 4, R"eeex(unsigned int)eeex", R"eeex(m_dwGreenMask)eeex"},
        FieldDesc{0x14, 4, R"eeex(unsigned int)eeex", R"eeex(m_dwBlueMask)eeex"},
        FieldDesc{0x18, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_bFadeTo)eeex"},
        FieldDesc{0x19, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_nFade)eeex"},
        FieldDesc{0x20, 8, R"eeex(SDL_Window*)eeex", R"eeex(m_pWindow)eeex"},
        FieldDesc{0x28, 8, R"eeex(void*)eeex", R"eeex(m_glContext)eeex"},
        FieldDesc{0x30, 288, R"eeex(:ref:`CVidBitmap<CVidBitmap>`)eeex", R"eeex(m_circle)eeex"},
        FieldDesc{0x150, 4, R"eeex(int)eeex", R"eeex(nWidth)eeex"},
        FieldDesc{0x154, 4, R"eeex(int)eeex", R"eeex(nHeight)eeex"},
        FieldDesc{0x158, 1, R"eeex(bool)eeex", R"eeex(bRedrawEntireScreen)eeex"},
        FieldDesc{0x159, 1, R"eeex(bool)eeex", R"eeex(bHardwareMouseCursor)eeex"},
        FieldDesc{0x160, 8, R"eeex(:ref:`CVidCell<CVidCell>`\*)eeex", R"eeex(pPointerVidCell)eeex"},
        FieldDesc{0x168, 8, R"eeex(:ref:`CVidCell<CVidCell>`\*)eeex", R"eeex(pTooltipVidCell)eeex"},
        FieldDesc{0x170, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_bPrintScreen)eeex"},
        FieldDesc{0x174, 4, R"eeex(unsigned int)eeex", R"eeex(nTickCount)eeex"},
        FieldDesc{0x178, 4, R"eeex(float)eeex", R"eeex(m_fInputScale)eeex"},
        FieldDesc{0x17C, 4, R"eeex(unsigned int)eeex", R"eeex(rgbGlobalTint)eeex"},
        FieldDesc{0x180, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_nGammaCorrection)eeex"},
        FieldDesc{0x181, 1, R"eeex(unsigned __int8)eeex", R"eeex(m_nBrightnessCorrection)eeex"},
        FieldDesc{0x184, 4, R"eeex(int)eeex", R"eeex(m_nScreenScrollY)eeex"},
        FieldDesc{0x188, 4, R"eeex(int)eeex", R"eeex(m_nScreenScrollX)eeex"},
        FieldDesc{0x18C, 4, R"eeex(int)eeex", R"eeex(nRShift)eeex"},
        FieldDesc{0x190, 4, R"eeex(int)eeex", R"eeex(nGShift)eeex"},
        FieldDesc{0x194, 4, R"eeex(int)eeex", R"eeex(nBShift)eeex"},
        FieldDesc{0x198, 4, R"eeex(tagRGBQUAD)eeex", R"eeex(rgbTint)eeex"},
        FieldDesc{0x19C, 4, R"eeex(int)eeex", R"eeex(bPointerEnabled)eeex"},
        FieldDesc{0x1A0, 16, R"eeex(:ref:`CRect<CRect>`)eeex", R"eeex(rPointerStorage)eeex"},
        FieldDesc{0x1B0, 16, R"eeex(:ref:`CRect<CRect>`)eeex", R"eeex(m_rLockedRect)eeex"},
        FieldDesc{0x1C0, 8, R"eeex(:ref:`CVidCell<CVidCell>`\*)eeex", R"eeex(m_lastCursor)eeex"},
        FieldDesc{0x1C8, 4, R"eeex(int)eeex", R"eeex(m_lastCursorFrame)eeex"},
        FieldDesc{0x1CC, 4, R"eeex(int)eeex", R"eeex(m_lastCursorSequence)eeex"},
        FieldDesc{0x1D0, 4, R"eeex(int)eeex", R"eeex(m_lastCursorNumber)eeex"},
        FieldDesc{0x1D4, 4, R"eeex(unsigned int)eeex", R"eeex(m_lastCursorFlags)eeex"},
        FieldDesc{0x1D8, 4, R"eeex(unsigned int)eeex", R"eeex(m_lastCursorResId)eeex"},
        FieldDesc{0x1E0, 8, R"eeex(SDL_Cursor*)eeex", R"eeex(m_hwCursor)eeex"},
        FieldDesc{0x1E8, 8, R"eeex(SDL_Surface*)eeex", R"eeex(m_hwCursorSurface)eeex"},
        FieldDesc{0x1F0, 4, R"eeex(int)eeex", R"eeex(nVRamSurfaces)eeex"},
        FieldDesc{0x1F8, 288, R"eeex(:ref:`CVidBitmap<CVidBitmap>`)eeex", R"eeex(m_rgbMasterBitmap)eeex"},
    }};
    inline constexpr LayoutDesc CVidModeLayout{0x318, static_cast<std::uint32_t>(CVidModeFields.size())};

}
